In [297]:
import pandas as pd
import numpy as np
import os
import math
from datetime import datetime
from IPython.display import display, Markdown

pd.set_option('display.max_colwidth', None)

In [298]:
# Load mom and dad's bank statements
data_path = r'data/'
sabbadel_columns = ['date', 'name', 'fin_date', 'value', 'account', 'nan', 'code']
bank_statements = []

for file in os.listdir(data_path):
    if file.endswith(".txt"):
        filepath = os.path.join(data_path, file)
        bank_statement = pd.read_csv(filepath, 
                                     sep='|', 
                                     header=None, 
                                     names=sabbadel_columns, 
                                     encoding='latin1')
        if 'ma' in file:
            bank_statement['who'] = 'ma'
        if 'pa' in file:
            bank_statement['who'] = 'pa'

        bank_statements.append(bank_statement)

parent_statements = pd.concat(bank_statements)

# Correct values
parent_statements['date'] = pd.to_datetime(parent_statements['date'], dayfirst=True)
parent_statements = parent_statements.drop(['nan', 'fin_date', 'account', 'code'], axis=1)
parent_statements = parent_statements.drop_duplicates()

In [299]:
# Load my bank statements
bank_statements = []

for file in os.listdir(data_path):
    if file.endswith(".xls"):
        filepath = os.path.join(data_path, file)
        bank_statement = pd.read_excel(filepath, skiprows=7) # the first 7 rows are account statistics, not transactions
        bank_statements.append(bank_statement)

my_statements = pd.concat(bank_statements)

# Standardize my bank statements
my_statements['date'] = pd.to_datetime(my_statements['FECHA VALOR'], dayfirst=True)
my_statements = my_statements.drop(['FECHA OPERACIÓN', 'SALDO', 'FECHA VALOR'], axis=1)
my_statements = my_statements.rename(columns={
    'CONCEPTO': 'name',
    'IMPORTE EUR': 'value'
})
my_statements = my_statements.drop_duplicates()[['date','name','value']]

In [300]:
# Define exclusion and inclusion strings and function
include = [
    "SUPER VINI",
    "ALCAMPO",
    "MARKET",
    "FRUTA",
    "mercadona",
    "carniceria",
    "veterinaria",
    "carref",
    "hiper",
    "papa jonhs",
    "polleria",
    "organic shop",
    "LIDL",
    "alejandro",
    "SANTIAGO",
    "Amon",
    "SEGUROS ADESLAS",
    "ELECTRICIDAD IBERDROLA",
    "AGUA CANAL",
    "LAS ROZAS",
    "ELECTRICIDAD FACTOR ENERGIA",
    "PESCADERIA",
    "dulce",
    "quesos",
    "paladar",
    "IBER LIMOSTAR",
    "TELEFONOS SIMYO",
    "HELADERIA"
    ]
include = [s.lower().strip() for s in include]

exclude = [
    "IKEA",
    "EL CORTE INGLES",
    "LEROY MERLIN",
    "AUTOESCUELA",
    "XE EUROPE",
    "Decorabano-Armilla",
    "Arciniega",
    "TRASPASO",
    "IBERIA",
    "COMISIONES",
    "INTERESES",
    "RECARGA",
    "IBERDROLA OTROS 2",
    "Ibkr",
    ]
exclude = [s.lower().strip() for s in exclude]

def filter_rows(df):
    df_in  = df[df['name'].str.contains('|'.join(include), case=False, na=False)]
    df_in = df_in[~df_in['name'].str.contains('|'.join(exclude), case=False, na=False)]

    df_ex  = df[~df['name'].isin(df_in['name'])]

    return df_in, df_ex


parent_included, parent_excluded = filter_rows(parent_statements)
my_included, my_excluded = filter_rows(my_statements)

In [301]:
# Define calculation functions
def get_previous_month(month, year):
    month -= 1
    if month == 0:
        month = 12
        year = year - 1

    return month, year


def filter_statements_by_date(df, month, year):
    months_df = df[(df['date'].dt.month == month) & (df['date'].dt.year == year)]

    return months_df


def calculate_payment(month, year, remainder):
    my_costs = filter_statements_by_date(my_included, month, year)
    parent_costs = filter_statements_by_date(parent_included, month, year)

    cash_paid = pd.read_csv(r'data/cash_paid.csv')
    previous_payment = cash_paid[cash_paid['month'] == month]['cash']

    total_costs = parent_costs['value'].sum() - my_costs['value'].sum() - previous_payment + remainder
    current_payment = round(-total_costs/4, -1)

    return current_payment


month, year = get_previous_month(datetime.now().month, datetime.now().year)
new_payment = calculate_payment(month, year, remainder=3).item() ###################################################### UPDATE REMAINDER ##################################################
print(f'{new_payment} EUR for {datetime.now().strftime("%B")}')

# Update cash_paid
cash_paid = pd.read_csv(r'data/cash_paid.csv')
if cash_paid.tail(1)['month'].iloc[0] == month:
    pd.concat([cash_paid, pd.DataFrame({'cash': new_payment, 
                                        'month': datetime.now().month, 
                                        'year': datetime.now().year}
                                        , index=[0])]).to_csv(r'data/cash_paid.csv', index=False)
elif not cash_paid.empty and (cash_paid.tail(1)['month'].iloc[0] == month + 1) and (cash_paid.tail(1)['cash'].iloc[0] != new_payment):
    cash_paid.loc[cash_paid.index[-1], 'cash'] = new_payment 
    cash_paid.to_csv(r'data/cash_paid.csv', index=False)

330.0 EUR for August

In [302]:
pd.set_option('display.max_rows', None)

print()
display(Markdown("# Excluded from calculation"))
display(filter_statements_by_date(parent_excluded, month, year))

print()
display(Markdown("# Included in calculation"))
display(filter_statements_by_date(parent_included, month, year))

# Excluded from calculation

,date,name,value,who
2,2024-07-29,COMPRA TARJ. 5402XXXXXXXX9016 IKEA LAS ROZAS HFB-CARRETERA DE,-1.50,ma
3,2024-07-29,COMPRA TARJ. 5402XXXXXXXX9016 IKEA LAS ROZAS HFB-CARRETERA DE,-3.50,ma
4,2024-07-29,ABONO BIZUM DE JANETH VERONICA MONTALVAN,20.00,ma
6,2024-07-26,COMPRA TARJ. 5402XXXXXXXX9016 MUY MUCHO ATOCHA-MADRID,-3.49,ma
9,2024-07-23,COMPRA TARJ. 5402XXXXXXXX9016 PRIMOR GRAN VIA-MADRID,-33.81,ma
12,2024-07-17,COMPRA TARJ. 5402XXXXXXXX9016 GIOELIA MADRID-MADRID,-8.70,ma
13,2024-07-17,COMPRA TARJ. 5402XXXXXXXX9016 JULIAN LOPEZ MADRID-MADRID,-28.40,ma
15,2024-07-15,COMPRA TARJ. 5402XXXXXXXX9016 DECATHLON ESPANA SAU-MADRID,-5.99,ma
16,2024-07-15,COMPRA TARJ. 5402XXXXXXXX9016 GRANIER ATOCHA-MADRID,-11.40,ma
17,2024-07-15,COMPRA TARJ. 5402XXXXXXXX9016 MISS KITS MADRID-MADRID,-25.88,ma
18,2024-07-15,COMPRA TARJ. 5402XXXXXXXX9016 MISS KITS MADRID-MADRID,-61.72,ma
21,2024-07-01,COMPRA TARJ. 5402XXXXXXXX9016 CONSULADO DE RU-MADRID,-86.00,ma
5,2024-07-26,COMPRA TARJ. 5402XXXXXXXX3027 GALAPAGOS-MADRID,-14.00,pa
6,2024-07-26,COMPRA TARJ. 5402XXXXXXXX3027 GALAPAGOS-MADRID,-6.00,pa
7,2024-07-26,COMPRA TARJ. 5402XXXXXXXX3027 AYTO.MADRID-DEPORTES-MADRID,-6.00,pa
8,2024-07-25,TRANSFERENCIA A XE Europe BV,-202.99,pa
10,2024-07-23,COMPRA TARJ. 5402XXXXXXXX3027 INSTITUTO CERVANTES-MADRID,-134.00,pa
11,2024-07-23,TRASPASO A 0569-00030808-14 XOK265L6PVP255MIC,-100.00,pa
15,2024-07-19,"ELECTRICIDAD IBERDROLA CLIENTES,SA IBERDROLA OTROS 2",-11.94,pa
17,2024-07-15,TRANSFERENCIA FRANCISCO JAVIER MARTINEZ BENITO,26.00,pa
18,2024-07-15,TRANSFERENCIA FRANCISCO JAVIER MARTINEZ BENITO,25.06,pa
21,2024-07-15,COMPRA TARJ. 5402XXXXXXXX3027 LEROY MERLIN LAS ROZAS-LAS ROZAS,-30.27,pa
22,2024-07-11,ADEUDO RECIBO CP ARCINIEGA 13,-426.06,pa
28,2024-07-05,COMPRA TARJ. 5402XXXXXXXX3027 IKEA LAS ROZAS HFB-CARRETERA DE,-10.48,pa
31,2024-07-04,TRANSFERENCIA FRANCISCO JAVIER MARTINEZ BENITO,1236.00,pa
32,2024-07-04,COMPRA TARJ. 5402XXXXXXXX3027 IKEA LAS ROZAS HFB-CARRETERA DE,-1.49,pa
0,2024-07-25,COMPRA TARJ. 5402XXXXXXXX6027 AIR EUROPA-LLUCMAJOR,-828.40,pa
1,2024-07-23,TRASPASO 0569-00035406-62 XOK265L6PVP255MIC,100.00,pa
2,2024-07-09,COMPRA TARJ. 5402XXXXXXXX6027 OBRAMAT USERA-MADRID,-5.75,pa
3,2024-07-01,COMPRA TARJ. 5402XXXXXXXX6027 SIMYO-POZUELO DE AL,-5.00,pa

# Included in calculation

,date,name,value,who
0,2024-07-31,COMPRA TARJ. 5402XXXXXXXX9016 MARKET LAS ROZA-LAS ROZAS,-14.57,ma
1,2024-07-31,COMPRA TARJ. 5402XXXXXXXX9016 MERCADONA C.C. EUROPOLIS-LAS ROZAS,-27.30,ma
5,2024-07-26,COMPRA TARJ. 5402XXXXXXXX9016 PAPA JOHNS - LAS ROZAS-LAS ROZAS DE,-19.98,ma
7,2024-07-23,COMPRA TARJ. 5402XXXXXXXX9016 FRUTAS AZAHARA-COLLADO VILLA,-3.39,ma
8,2024-07-23,COMPRA TARJ. 5402XXXXXXXX9016 HELADERIA DON NINO-MADRID,-47.00,ma
10,2024-07-22,COMPRA TARJ. 5402XXXXXXXX9016 CLINICA VETERINARIA ESCLA-LAS ROZAS DE,-38.00,ma
11,2024-07-17,COMPRA TARJ. 5402XXXXXXXX9016 IBER LIMOSTAR-FUENLABRADA,-11.50,ma
14,2024-07-15,COMPRA TARJ. 5402XXXXXXXX9016 IBER LIMOSTAR-FUENLABRADA,-35.95,ma
19,2024-07-04,COMPRA TARJ. 5402XXXXXXXX9016 CLINICA VETERINARIA ESCLA-LAS ROZAS DE,-7.00,ma
20,2024-07-01,COMPRA TARJ. 5402XXXXXXXX9016 MARKET LAS ROZA-LAS ROZAS,-7.00,ma
0,2024-07-30,TELEFONOS SIMYO Simyo,-27.99,pa
1,2024-07-30,"ELECTRICIDAD IBERDROLA CLIENTES,SA IBERDROLA ELECTRI",-88.86,pa
2,2024-07-29,COMPRA TARJ. 5402XXXXXXXX3027 EL HIPER DE LA FRUTA-LAS ROZAS DE,-16.19,pa
3,2024-07-29,COMPRA TARJ. 5402XXXXXXXX3027 SUPER VINI-ROZAS LAS,-4.98,pa
4,2024-07-29,COMPRA TARJ. 5402XXXXXXXX3027 MARKET LAS ROZA-LAS ROZAS,-59.66,pa
9,2024-07-24,COMPRA TARJ. 5402XXXXXXXX3027 CLINICA VETERINARIA ESCLA-LAS ROZAS DE,-125.00,pa
12,2024-07-22,COMPRA TARJ. 5402XXXXXXXX3027 MARKET LAS ROZA-LAS ROZAS,-45.74,pa
13,2024-07-22,COMPRA TARJ. 5402XXXXXXXX3027 EL HIPER DE LA FRUTA-LAS ROZAS DE,-21.74,pa
14,2024-07-19,"AGUA CANAL DE ISABEL II, SOCIEDAD A RECIBO CONTRATO 3",-34.56,pa
16,2024-07-18,COMPRA TARJ. 5402XXXXXXXX3027 SUPER VINI-ROZAS LAS,-9.45,pa
19,2024-07-15,COMPRA TARJ. 5402XXXXXXXX3027 MARKET LAS ROZA-LAS ROZAS,-49.42,pa
20,2024-07-15,COMPRA TARJ. 5402XXXXXXXX3027 EL HIPER DE LA FRUTA-LAS ROZAS DE,-25.22,pa
23,2024-07-11,COMPRA TARJ. 5402XXXXXXXX3027 LIDL LAS ROZAS DE MADRID--ROZAS LAS,-4.28,pa
24,2024-07-10,"ELECTRICIDAD FACTOR ENERGIA, S.A GFN2400492161 ES0",-26.32,pa
25,2024-07-09,COMPRA TARJ. 5402XXXXXXXX3027 SUPER VINI-ROZAS LAS,-1.98,pa
26,2024-07-09,COMPRA TARJ. 5402XXXXXXXX3027 CARNICERIA DEL ALBA-MADRID,-25.40,pa
27,2024-07-08,DEVOLUCION TAR.5402XXXXXXXX3027 07.07 LIDL LAS ROZAS DE MADRID--ROZAS LAS,2.99,pa
29,2024-07-05,COMPRA TARJ. 5402XXXXXXXX3027 LIDL LAS ROZAS DE MADRID--ROZAS LAS,-4.28,pa
30,2024-07-05,DEVOLUCION TAR.5402XXXXXXXX3027 05.07 LIDL LAS ROZAS DE MADRID--ROZAS LAS,2.49,pa
33,2024-07-04,COMPRA TARJ. 5402XXXXXXXX3027 LIDL LAS ROZAS DE MADRID--ROZAS LAS,-9.96,pa
34,2024-07-04,COMPRA TARJ. 5402XXXXXXXX3027 PAPA JOHNS - LAS ROZAS-LAS ROZAS DE,-23.17,pa
35,2024-07-02,SEGUROS ADESLAS MADRID,-37.50,pa
36,2024-07-01,ADEUDO RECIBO C.P. SANTIAGO AMON 2,-158.94,pa
37,2024-07-01,COMPRA TARJ. 5402XXXXXXXX3027 MARKET LAS ROZA-LAS ROZAS,-60.27,pa
38,2024-07-01,COMPRA TARJ. 5402XXXXXXXX3027 EL HIPER DE LA FRUTA-LAS ROZAS DE,-20.37,pa
39,2024-07-01,COMPRA TARJ. 5402XXXXXXXX3027 SUPER VINI-ROZAS LAS,-2.73,pa
40,2024-07-01,COMPRA TARJ. 5402XXXXXXXX3027 SUPER VINI-LAS ROZAS,-1.98,pa

In [303]:
print()
display(Markdown("# Mine excluded from calculation"))
display(filter_statements_by_date(my_excluded, month, year))

print()
display(Markdown("# Mine indcluded calculation"))
display(filter_statements_by_date(my_included, month, year))

# Mine excluded from calculation

,date,name,value
1,2024-07-27,Reintegro Contra Cuenta En Atm 004951820001 El 27/07/2024 A Las 13:50. .pan: 5489010369724776.,-20.00
2,2024-07-29,"Transferencia De Educadvisor, S.l., Concepto Abono Nomina 07/2024.",2105.89
3,2024-07-21,"Compra Mgp*wallapop S 0402593, Barcelona, Tarjeta 5489010369724776 , Comision 0,00",-20.80
4,2024-07-21,"Compra Aliexpress, London, Tarjeta 5489010369724776 , Comision 0,00",-48.25
6,2024-07-20,"Transaccion Contactless En Leroy Merlin La, Las Rozas, Tarj. :*724776",-25.98
7,2024-07-20,"Transaccion Contactless En Leroy Merlin La, Las Rozas, Tarj. :*724776",-18.73
9,2024-07-15,"Transaccion Contactless En El Corte Ingles, Madrid, Tarj. :*724776",-18.09
11,2024-07-07,"Compra Mgp*wallapop S 0402593, Barcelona, Tarjeta 5489010369724776 , Comision 0,00",-100.69
12,2024-07-07,"Transaccion Contactless En Metro De Madrid, Madrid, Tarj. :*724776",-6.10
13,2024-07-06,Reintegro Contra Cuenta En Atm 004951820020 El 06/07/2024 A Las 19:45. .pan: 5489010369724776.,-260.00
15,2024-07-05,"Reintegro Cajero Servired, Atm:00815735, Madrid, Tarj. :*724776, Comis. Cajero Servired,importe:1,80",-521.80
16,2024-07-01,"Devolucion Compra En Mgp*wallapop S 0402593, Barcelona, Tarjeta 5489010369724776 , Comision 0,00",434.18
17,2024-07-03,"Transaccion Contactless En Renfe Cercanias, Rozas De Madr, Tarj. :*724776",-10.00
18,2024-07-01,"Transferencia De Educadvisor, S.l., Concepto Abono Nomina 06/2024.",2456.88

# Mine indcluded calculation

,date,name,value
0,2024-07-29,"Transaccion Contactless En Market Las Roza, Las Rozas, Tarj. :*724776",-3.73
5,2024-07-20,"Transaccion Contactless En Lidl Las Rozas, Rozas Las, Tarj. :*724776",-5.78
8,2024-07-17,"Transaccion Contactless En Market Las Roza, Las Rozas, Tarj. :*724776",-7.88
10,2024-07-15,"Transaccion Contactless En Alcampo28029-va, Madrid, Tarj. :*724776",-15.67
14,2024-07-05,"Transaccion Contactless En Market Las Roza, Las Rozas, Tarj. :*724776",-6.82