In [22]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException, TimeoutException, ElementNotInteractableException, ElementClickInterceptedException   
from datetime import datetime
import traceback
import os
import pandas as pd
import re
import numpy as np
from time import sleep
import urllib.parse

pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)

In [23]:
directory = 'data/listings/'
dfs = []
for filename in os.listdir(directory):
    if filename.endswith(".csv"):
        filepath = os.path.join(directory, filename)
        df = pd.read_csv(filepath)
        dfs.append(df)
listings = pd.concat(dfs)
listings.to_csv('data/listings.csv', index=False)
listings

,title,href,product_id,object_id,listing_id,num_images,img_scr,date_last_scraped,date_first_scraped,price,featured,shipping,reserved,walla_pro,extra
0,SAMSUNG ZFOLD 6 + ACCESORIOS,https://es.wallapop.com/item/zfold-6---funda---watch-7---cargador-1030758668,NaN,9487,1030758668,0,https://cdn.wallapop.com/images/10420/h1/oq/__/c10420p1030758668/i5027604435.jpg?pictureSize=W320,05-08-24,NaN,2200.0,False,1,False,False,NaN
1,3 emisoras mas base circulo cerrado,https://es.wallapop.com/item/3-emisoras-mas-base-circulo-cerrado-293747487,NaN,9487,293747487,0,https://cdn.wallapop.com/images/10420/4u/w1/__/c10420p293747487/i659516464.jpg?pictureSize=W320,05-08-24,NaN,2200.0,False,0,False,False,NaN
2,FOLD 6 512 GB NEGRO CARBONO,https://es.wallapop.com/item/fold-6-512-gb-negro-carbono-1034986534,NaN,9487,1034986534,8,https://cdn.wallapop.com/images/10420/h4/7c/__/c10420p1034986534/i5050123096.jpg?pictureSize=W640,05-08-24,NaN,2200.0,False,0,False,False,NaN
3,Samsung Z Fold 6 512 GB Gris,https://es.wallapop.com/item/samsung-z-fold-6-512-gb-gris-1034155101,NaN,9487,1034155101,2,https://cdn.wallapop.com/images/10420/h3/pj/__/c10420p1034155101/i5044472855.jpg?pictureSize=W640,05-08-24,NaN,2200.0,False,1,False,False,NaN
4,iPhone,https://es.wallapop.com/item/iphone-1019048870,NaN,9487,1019048870,5,https://cdn.wallapop.com/images/10420/gu/pr/__/c10420p1019048870/i4968101627.jpg?pictureSize=W640,05-08-24,NaN,2210.0,False,1,False,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1908,Móvil LG KF700,https://es.wallapop.com/item/movil-lg-kf700-1034647771,NaN,10175,1034647771,8,https://cdn.wallapop.com/images/10420/h4/03/__/c10420p1034647771/i5047772392.jpg?pictureSize=W640,05-08-24,NaN,4.0,False,1,False,False,NaN
1909,Teléfono forma,https://es.wallapop.com/item/telefono-forma-957111993,NaN,10175,957111993,0,https://cdn.wallapop.com/images/10420/ft/u8/__/c10420p957111993/i4607137800.jpg?pictureSize=W320,05-08-24,NaN,4.0,False,1,False,False,NaN
1910,Movil LG Optimus L3 (Blanco),https://es.wallapop.com/item/lg-955789919,NaN,10175,955789919,5,https://cdn.wallapop.com/images/10420/ft/1w/__/c10420p955789919/i3601637313.jpg?pictureSize=W640,05-08-24,NaN,4.0,False,1,False,False,NaN
1911,Movil LG Optimus L3 (Negro),https://es.wallapop.com/item/movil-lg-optimus-l3-negro-955788569,NaN,10175,955788569,5,https://cdn.wallapop.com/images/10420/ft/1v/__/c10420p955788569/i3601638449.jpg?pictureSize=W640,05-08-24,NaN,4.0,False,1,False,False,NaN
1912,Tapa trasera titanio (Nokia 8850),https://es.wallapop.com/item/tapa-trasera-titanio-nokia-8850-984917259,NaN,10175,984917259,5,https://cdn.wallapop.com/images/10420/ga/e7/__/c10420p984917259/i4770273723.jpg?pictureSize=W640,05-08-24,NaN,4.0,False,1,False,False,NaN

In [61]:
pd.read_csv('data/listings.csv')

,title,https://es.wallapop.com/item/,product_id,object_id,listing_id,num_images,date_last_scraped,date_first_scraped,price,featured,shipping,reserved,walla_pro
0,SAMSUNG ZFOLD 6 + ACCESORIOS,zfold-6---funda---watch-7---cargador-1030758668,NaN,9487,1030758668,0,50824,NaN,220000,0,1,0,0
1,3 emisoras mas base circulo cerrado,3-emisoras-mas-base-circulo-cerrado-293747487,NaN,9487,293747487,0,50824,NaN,220000,0,0,0,0
2,FOLD 6 512 GB NEGRO CARBONO,fold-6-512-gb-negro-carbono-1034986534,NaN,9487,1034986534,8,50824,NaN,220000,0,0,0,0
3,Samsung Z Fold 6 512 GB Gris,samsung-z-fold-6-512-gb-gris-1034155101,NaN,9487,1034155101,2,50824,NaN,220000,0,1,0,0
4,iPhone,iphone-1019048870,NaN,9487,1019048870,5,50824,NaN,221000,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
280584,Móvil LG KF700,movil-lg-kf700-1034647771,NaN,10175,1034647771,8,50824,NaN,400,0,1,0,0
280585,Teléfono forma,telefono-forma-957111993,NaN,10175,957111993,0,50824,NaN,400,0,1,0,0
280586,Movil LG Optimus L3 (Blanco),lg-955789919,NaN,10175,955789919,5,50824,NaN,400,0,1,0,0
280587,Movil LG Optimus L3 (Negro),movil-lg-optimus-l3-negro-955788569,NaN,10175,955788569,5,50824,NaN,400,0,1,0,0
280588,Tapa trasera titanio (Nokia 8850),tapa-trasera-titanio-nokia-8850-984917259,NaN,10175,984917259,5,50824,NaN,400,0,1,0,0