In [167]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException, TimeoutException, ElementNotInteractableException, ElementClickInterceptedException   
from datetime import datetime
import traceback

import pandas as pd
import re
import numpy as np
from time import sleep
import urllib.parse

pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 50)

In [168]:
# Set up functions
def print_update(func):
    def wrapper(*args, **kwargs):
        print(f'Running {func.__name__}')
        return func(*args, **kwargs)
    return wrapper


def reject_cookies(driver, temp=0, retries=2):
    try:
        WebDriverWait(driver, retries).until(EC.element_to_be_clickable((By.ID, 'onetrust-reject-all-handler')))
        driver.find_element(By.ID, 'onetrust-reject-all-handler').click()
    except (NoSuchElementException, TimeoutException, ElementNotInteractableException, ElementClickInterceptedException):
        if temp >= retries:
            print(f'{retries} attempts failed to Reject cookies')
        else:
            reject_cookies(driver, temp + 1)


def skip_tutorial(driver, temp=0, retries=2):
    try:
        WebDriverWait(driver, retries).until(EC.element_to_be_clickable((By.CSS_SELECTOR, 'walla-button.TooltipWrapper__skip')))
        driver.find_element(By.CSS_SELECTOR, 'walla-button.TooltipWrapper__skip').click()
        driver.find_element(By.CSS_SELECTOR, 'walla-button.TooltipWrapper__skip').click()
        driver.find_element(By.CSS_SELECTOR, 'walla-button.TooltipWrapper__skip').click()
    except (NoSuchElementException, TimeoutException, ElementNotInteractableException, ElementClickInterceptedException):
        if temp >= retries:
            print(f'{temp} attempts failed to Skip the tutorial')
        else:
            skip_tutorial(driver, temp + 1)

@print_update
def setup_driver():
    options = webdriver.ChromeOptions()
    prefs = {"profile.managed_default_content_settings.images": 2}
    options.add_experimental_option("prefs", prefs)
    # options.add_argument("--headless")
    options.add_argument("--window-size=1920,1080")
    options.add_argument("--log-level=4")
    options.add_argument("--disable-extensions")
    driver = webdriver.Chrome(options=options)
    driver.maximize_window()

    driver.get('https://es.wallapop.com/app/search?filters_source=category_navigation&latitude=40.41956&longitude=-3.69196')

    reject_cookies(driver)
    skip_tutorial(driver)

    return driver

@print_update
def get_explorer_urls(product_id=None, category_id=24200):
    # gets the corresponding urls to wallapop listing explorer
    base = 'https://es.wallapop.com/app/search?'
    urls = []

    if product_id:
        pass ## Do later
        # url = url if (product_id == None) else url + f'keywords={urllib.parse.quote(product_id)}&'
    else:
        '''
        Make a df for every category 
        Get the histogram curve for each category type by querying the listings db
        '''


        if category_id == 24200:
            object_type_ids = [9447, 9487, 10175, 24102]
            object_type_ids = [9447]
            for object_id in object_type_ids:
                url = base + f'category_ids={category_id}&filters_source=quick_filters&latitude=40.41956&longitude=-3.69196&object_type_ids={object_id}&'
                urls += split_explorer_url(url, product_id=product_id, category_id=category_id, object_id=object_id)
        else:
            print('category not supported')

    return urls


def split_explorer_url(url, product_id=None, category_id=None, object_id=None):
    # breaks up url into smaller subsets to divide up scrape load
    urls = []

    if product_id:
        # IGNORE write later after figuring out product_id classification module
        pass
    else:
        start, increment, loops = 0, 4, 12
        current_range = increment

        for i in range(loops):
            min = start
            max = start + current_range

            if i == 0:
                pricequery = f'max_sale_price={max}'
            elif i + 1 == len(range(loops)):
                pricequery = f'min_sale_price={min+.01}'
            else:
                pricequery = f'min_sale_price={min+.01}&max_sale_price={max}'

            start += current_range
            current_range += increment + (i-1)**2 # Ramps up range ~according to previous scrapes

            urls.append({
                'explorer_url': url + pricequery,
                'product_id': product_id,
                'category_id': category_id,
                'object_id': object_id,
                'date_scraped': np.nan,
                'scrape_empty': np.nan,
                'scrape_incomplete': np.nan,
                'redundant_url': np.nan,
            })
    return urls


def load_more(driver, temp=0, retries=2):
    # Clicks button that initiates infinite scroll dynamic listings
    try:
        WebDriverWait(driver, retries).until(EC.element_to_be_clickable((By.ID, 'btn-load-more')))
        driver.find_element(By.ID, 'btn-load-more').click()
    except (NoSuchElementException, TimeoutException, ElementNotInteractableException, ElementClickInterceptedException):
        if temp >= retries:
            print(f'{temp} attempts failed to Click the load button')
        else:
            load_more(driver, temp + 1)


def wait_listings(driver, temp=0, retries=3):
    try:
        WebDriverWait(driver, retries).until(EC.element_to_be_clickable((By.CSS_SELECTOR, 'a.ItemCardList__item')))
        return True
    except (NoSuchElementException, TimeoutException, ElementNotInteractableException, ElementClickInterceptedException):
        if temp >= retries:
            print(f'{temp} attempts failed to Find listings')
        else:
            wait_listings(driver, temp + 1)

In [172]:
df = pd.read_csv('data/categories/24200/10414.csv')
df[df['date_last_scraped'] != df['date_first_scraped']]

Empty DataFrame
Columns: [title, https://es.wallapop.com/item/, object_id, listing_id, num_images, date_last_scraped, date_first_scraped, price_cents, featured, shipping, reserved, walla_pro]
Index: []

In [170]:
# Explorer function
@print_update
def scrape_explorer(driver, object_id=None):
    # Scrapes listings displayed in explorer
    scrapings = []
    cards = driver.find_elements(By.CSS_SELECTOR, 'a.ItemCardList__item')
    for card in cards:
        title = card.get_attribute('title')
        href = card.get_attribute('href')
        href = href.split('https://es.wallapop.com/item/')[-1]
        listing_id = href.split('-')[-1]
        num_images = len(card.find_elements(By.TAG_NAME, 'li'))
        if not num_images:
            num_images = 1
        date_scraped = datetime.now().strftime('%d%m%y%H%M%S')

        price = card.find_element(By.CSS_SELECTOR, 'span.ItemCard__price').text.strip()
        price = float(re.sub(r'[^\d,]', '', price).replace(',', '.'))
        price = int(price*100)
        
        try:
            if card.find_element(By.CSS_SELECTOR, 'p.ItemCard__highlight-text.pb-2'):
                featured = 1
            else:
                featured = 0
        except NoSuchElementException:
            featured = 0

        shadow_hosts = card.find_elements(By.CSS_SELECTOR, 'wallapop-badge')
        shipping, reserved, walla_pro = 0, 0, 0
        for shadow_host in shadow_hosts:
            shadow_root = driver.execute_script('return arguments[0].shadowRoot', shadow_host)
            span = shadow_root.find_element(By.CSS_SELECTOR, 'span').text.strip() 
            if span == 'Sólo venta en persona':
                shipping = 0
            elif span == 'Envío disponible':
                shipping = 1
            elif span == 'Envío gratis':
                shipping = 2
            elif span == 'Reservado':
                reserved = 1
            elif span == 'Reacondicionado':
                walla_pro = 1
            else:
                print('\nUNEXPECTED SHADOW_ROOT DATA\n')

        scrapings.append({
            'title': title,
            'https://es.wallapop.com/item/': href,
            'object_id': object_id,
            'listing_id': listing_id,
            'num_images': num_images,
            'date_last_scraped': date_scraped,
            'date_first_scraped': date_scraped,
            'price_cents': price,
            'featured': featured,
            'shipping': shipping,
            'reserved': reserved,
            'walla_pro': walla_pro,
        })
        
    return pd.DataFrame(scrapings)

@print_update
def scroll_explorer(driver, max_scrolls=50, category_id=None, object_id=None):
    global scraped_df
    previous_height = driver.execute_script("return document.body.scrollHeight")
    sleep_time = 0.1
    count = 0
    timer = datetime.now()
    complete = False

    while True:
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        count += 1
        if count == max_scrolls:
            print('    Scroll: Count reached')
            scraped_df, complete = check_scraping(driver, False, timer, category_id=category_id, object_id=object_id)

        try:
            WebDriverWait(driver, sleep_time).until(lambda driver: driver.execute_script("return document.body.scrollHeight") != previous_height)
            sleep_time /= 2
            previous_height = driver.execute_script("return document.body.scrollHeight")
        except TimeoutException:
            sleep_time += sleep_time
            if sleep_time > 12:
                print('    Scroll: Timed out')
                scraped_df, complete = check_scraping(driver, True, timer, category_id=category_id, object_id=object_id)

        if complete:
            return scraped_df, True

@print_update
def check_scraping(driver, timed_out, timer=None, category_id=None, object_id=None):
    if timed_out:
        pass
    else:
        sleep(1)
        
    # Get scrapings and check if they already exist in global
    scrapings_df = scrape_explorer(driver, object_id=object_id)

    if scrapings_df.empty:
        return scraped_df, True
    else:
        scraped_df = update_scraping(scrapings_df, category_id=category_id, object_id=object_id)
        clear_explorer(driver)

        # # Print stats
        timespent = datetime.now() - timer
        print(f'    scrapings took: {timespent}')
        print(f'    scrapings count: {len(scrapings_df)}')
        print(f'    scrapings efficiency = {len(scrapings_df)/timespent.total_seconds()}')
        if timed_out:
            return scraped_df, True
        else:
            return scroll_explorer(driver, category_id=category_id, object_id=object_id)


# def update_scraping(scrapings_df, category_id=None, object_id=None):
#     try:
#         object_df = pd.read_csv(f'data/categories/{category_id}/{object_id}.csv')
#         if scrapings_df['listing_id'].isin(object_df['listing_id']).all():
#             print('Scroll: Seen before')
#             return scraped_df
#         else:
#             object_df = pd.concat([object_df, scrapings_df]).drop_duplicates()
#             object_df.to_csv(f'data/categories/{category_id}/{object_id}.csv', index=False)

#         if scraped_df.empty:
#             scraped_df = scrapings_df
#             return scraped_df
#         else:
#             scraped_df = pd.concat([scraped_df, scrapings_df]).drop_duplicates()
#             return scraped_df

#     except FileNotFoundError:
#         if scraped_df.empty:
#             scraped_df = scrapings_df
#             scraped_df.to_csv(f'data/categories/{category_id}/{object_id}.csv', index=False)
#             return scraped_df
#         else:
#             scraped_df = pd.concat([scraped_df, scrapings_df]).drop_duplicates()
#             scraped_df.to_csv(f'data/categories/{category_id}/{object_id}.csv', index=False)
#             return scraped_df

@print_update
def update_scraping(scrapings_df, category_id=None, object_id=None):
    try:
        object_df = pd.read_csv(f'data/categories/{category_id}/{object_id}.csv')
        ignore_columns = ['date_first_scraped', 'date_last_scraped']
        compare_columns = [col for col in scrapings_df.columns if col not in ignore_columns]

        for _, row in scrapings_df.iterrows():
            match = object_df[compare_columns].eq(row[compare_columns]).all(axis=1)
            print(match)
            if match.any():
                object_df.loc[match, 'date_last_scraped'] = datetime.now().strftime('%d%m%y%H%M%S')
            else:
                object_df = pd.concat([object_df, pd.DataFrame([row])], ignore_index=True)
        
        object_df.to_csv(f'data/categories/{category_id}/{object_id}.csv', index=False)

        if 'scraped_df' not in globals():
            
            scraped_df = scrapings_df
        else:
            scraped_df = pd.concat([scraped_df, scrapings_df]).drop_duplicates()
        
        return scraped_df

    except FileNotFoundError:
        object_df = scrapings_df
        object_df.to_csv(f'data/categories/{category_id}/{object_id}.csv', index=False)
        return scrapings_df



@print_update
def clear_explorer(driver):
    driver.execute_script("window.scrollTo(0, 0);")
    try:
        # Find elements and delete all siblings
        element = driver.find_element(By.CSS_SELECTOR, 'a.ItemCardList__item')
        parent = element.find_element(By.XPATH, '..')
        siblings = parent.find_elements(By.XPATH, '*')
        for sibling in siblings:
            driver.execute_script("arguments[0].remove();", sibling)
    except NoSuchElementException:
        print('    No listings found to clear to clear')
   

def check_newest(category_ids=[24200, 12579, 13100]):
    for category_id in category_ids:
        category_start = datetime.now()

        try:
            categories = pd.read_csv('data/categories/categories.csv')
            object_type_ids = categories[categories['category_id'] == 24200]
            object_type_ids = object_type_ids[object_type_ids['subgroup_name'] != 'FULL_GROUP']
            # object_type_ids = object_type_ids[object_type_ids['last_checked'] != category_start.strftime('%d%m%y%H%M%S')]
        except FileNotFoundError:
            return 'data/categories/categories.csv is missing'
        category_name = categories.loc[categories['category_id'] == category_id, 'category_name'].values[0]
        print(f'\n=== Checking {category_name}')

        scraped_count = 0
        for object_id in object_type_ids['object_type_id']:
            object_name = categories.loc[categories['object_type_id'] == object_id, 'subgroup_name'].values[0]
            print(f'\nSCRAPING {object_name.upper()}')

            object_start = datetime.now()
            driver = setup_driver()
            driver.get(f'https://es.wallapop.com/app/search?object_type_ids={object_id}&category_ids={category_id}&filters_source=quick_filters&latitude=40.41956&longitude=-3.69196&order_by=newest')
            if wait_listings(driver):
                try:
                    load_more(driver)
                    scraped_df = pd.DataFrame()
                    scraped_df = scroll_explorer(driver, category_id=category_id, object_id=object_id)
                    driver.quit()
                except Exception as e:
                    print(f'{category_id}-{object_id} Error')
                    traceback.print_exc()
                    driver.quit()
                    return e
            else:
                driver.quit()

            # Update categories.csv
            categories.loc[categories['object_type_id'] == object_id, 'last_checked'] = datetime.now().strftime('%d%m%y%H%M%S')
            categories.to_csv('data/categories/categories.csv', index=False)

            timespent = datetime.now() - object_start
            scraped_count += len(scraped_df)
            print(f'\n{object_name.upper()} SCRAPE COMPLETE')
            print(f'    {object_name} took: {timespent}')
            print(f'    {object_name} scraped: {len(scraped_df)}')
            print(f'    {object_name} efficency: {len(scraped_df)/timespent.total_seconds()}')


        categories.loc[(categories['category_id'] == category_id) & (categories['subgroup_name'] == 'FULL_GROUP'), 'last_checked'] = datetime.now().strftime('%d%m%y%H%M%S')
        categories.to_csv('data/categories/categories.csv', index=False)

        timespent = datetime.now() - category_start
        print(f'\n{category_name} category checked')
        print(f'    {category_name} took: {timespent}')
        print(f'    {category_name} scraped: {scraped_count}')
        print(f'    {category_name} efficency: {scraped_count/timespent.total_seconds()}')

    
    print('\n=== All categories checked ===\n')

In [171]:
categories = [24200]

while True:
    try:
        message = check_newest(categories)
        if message:
            print(message)
            break
    except Exception:
        traceback.print_exc()
    sleep(5)

=== Checking Tecnología y electrónica

SCRAPING TV
Running setup_driver
Running scroll_explorer
    Scroll: Count reached
Running check_scraping
Running scrape_explorer
Running update_scraping
0       False
1       False
2       False
3       False
4       False
        ...
4109    False
4110    False
4111    False
4112    False
4113    False
Length: 4114, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4110    False
4111    False
4112    False
4113    False
4114    False
Length: 4115, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4111    False
4112    False
4113    False
4114    False
4115    False
Length: 4116, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4112    False
4113    False
4114    False
4115    False
4116    False
Length: 4117, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4113    False
4114    False
4115    False
4116    False
4117    False
Length: 4118, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4114    False
4115    False
4116    False
4117    False
4118    False
Length: 4119, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4115    False
4116    False
4117    False
4118    False
4119    False
Length: 4120, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4116    False
4117    False
4118    False
4119    False
4120    False
Length: 4121, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4117    False
4118    False
4119    False
4120    False
4121    False
Length: 4122, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4118    False
4119    False
4120    False
4121    False
4122    False
Length: 4123, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4119    False
4120    False
4121    False
4122    False
4123    False
Length: 4124, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4120    False
4121    False
4122    False
4123    False
4124    False
Length: 4125, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4121    False
4122    False
4123    False
4124    False
4125    False
Length: 4126, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4122    False
4123    False
4124    False
4125    False
4126    False
Length: 4127, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4123    False
4124    False
4125    False
4126    False
4127    False
Length: 4128, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4124    False
4125    False
4126    False
4127    False
4128    False
Length: 4129, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4125    False
4126    False
4127    False
4128    False
4129    False
Length: 4130, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4126    False
4127    False
4128    False
4129    False
4130    False
Length: 4131, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4127    False
4128    False
4129    False
4130    False
4131    False
Length: 4132, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4128    False
4129    False
4130    False
4131    False
4132    False
Length: 4133, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4129    False
4130    False
4131    False
4132    False
4133    False
Length: 4134, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4130    False
4131    False
4132    False
4133    False
4134    False
Length: 4135, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4131    False
4132    False
4133    False
4134    False
4135    False
Length: 4136, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4132    False
4133    False
4134    False
4135    False
4136    False
Length: 4137, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4133    False
4134    False
4135    False
4136    False
4137    False
Length: 4138, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4134    False
4135    False
4136    False
4137    False
4138    False
Length: 4139, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4135    False
4136    False
4137    False
4138    False
4139    False
Length: 4140, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4136    False
4137    False
4138    False
4139    False
4140    False
Length: 4141, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4137    False
4138    False
4139    False
4140    False
4141    False
Length: 4142, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4138    False
4139    False
4140    False
4141    False
4142    False
Length: 4143, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4139    False
4140    False
4141    False
4142    False
4143    False
Length: 4144, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4140    False
4141    False
4142    False
4143    False
4144    False
Length: 4145, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4141    False
4142    False
4143    False
4144    False
4145    False
Length: 4146, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4142    False
4143    False
4144    False
4145    False
4146    False
Length: 4147, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4143    False
4144    False
4145    False
4146    False
4147    False
Length: 4148, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4144    False
4145    False
4146    False
4147    False
4148    False
Length: 4149, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4145    False
4146    False
4147    False
4148    False
4149    False
Length: 4150, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4146    False
4147    False
4148    False
4149    False
4150    False
Length: 4151, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4147    False
4148    False
4149    False
4150    False
4151    False
Length: 4152, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4148    False
4149    False
4150    False
4151    False
4152    False
Length: 4153, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4149    False
4150    False
4151    False
4152    False
4153    False
Length: 4154, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4150    False
4151    False
4152    False
4153    False
4154    False
Length: 4155, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4151    False
4152    False
4153    False
4154    False
4155    False
Length: 4156, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4152    False
4153    False
4154    False
4155    False
4156    False
Length: 4157, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4153    False
4154    False
4155    False
4156    False
4157    False
Length: 4158, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4154    False
4155    False
4156    False
4157    False
4158    False
Length: 4159, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4155    False
4156    False
4157    False
4158    False
4159    False
Length: 4160, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4156    False
4157    False
4158    False
4159    False
4160    False
Length: 4161, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4157    False
4158    False
4159    False
4160    False
4161    False
Length: 4162, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4158    False
4159    False
4160    False
4161    False
4162    False
Length: 4163, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4159    False
4160    False
4161    False
4162    False
4163    False
Length: 4164, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4160    False
4161    False
4162    False
4163    False
4164    False
Length: 4165, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4161    False
4162    False
4163    False
4164    False
4165    False
Length: 4166, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4162    False
4163    False
4164    False
4165    False
4166    False
Length: 4167, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4163    False
4164    False
4165    False
4166    False
4167    False
Length: 4168, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4164    False
4165    False
4166    False
4167    False
4168    False
Length: 4169, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4165    False
4166    False
4167    False
4168    False
4169    False
Length: 4170, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4166    False
4167    False
4168    False
4169    False
4170    False
Length: 4171, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4167    False
4168    False
4169    False
4170    False
4171    False
Length: 4172, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4168    False
4169    False
4170    False
4171    False
4172    False
Length: 4173, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4169    False
4170    False
4171    False
4172    False
4173    False
Length: 4174, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4170    False
4171    False
4172    False
4173    False
4174    False
Length: 4175, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4171    False
4172    False
4173    False
4174    False
4175    False
Length: 4176, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4172    False
4173    False
4174    False
4175    False
4176    False
Length: 4177, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4173    False
4174    False
4175    False
4176    False
4177    False
Length: 4178, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4174    False
4175    False
4176    False
4177    False
4178    False
Length: 4179, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4175    False
4176    False
4177    False
4178    False
4179    False
Length: 4180, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4176    False
4177    False
4178    False
4179    False
4180    False
Length: 4181, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4177    False
4178    False
4179    False
4180    False
4181    False
Length: 4182, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4178    False
4179    False
4180    False
4181    False
4182    False
Length: 4183, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4179    False
4180    False
4181    False
4182    False
4183    False
Length: 4184, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4180    False
4181    False
4182    False
4183    False
4184    False
Length: 4185, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4181    False
4182    False
4183    False
4184    False
4185    False
Length: 4186, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4182    False
4183    False
4184    False
4185    False
4186    False
Length: 4187, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4183    False
4184    False
4185    False
4186    False
4187    False
Length: 4188, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4184    False
4185    False
4186    False
4187    False
4188    False
Length: 4189, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4185    False
4186    False
4187    False
4188    False
4189    False
Length: 4190, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4186    False
4187    False
4188    False
4189    False
4190    False
Length: 4191, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4187    False
4188    False
4189    False
4190    False
4191    False
Length: 4192, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4188    False
4189    False
4190    False
4191    False
4192    False
Length: 4193, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4189    False
4190    False
4191    False
4192    False
4193    False
Length: 4194, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4190    False
4191    False
4192    False
4193    False
4194    False
Length: 4195, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4191    False
4192    False
4193    False
4194    False
4195    False
Length: 4196, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4192    False
4193    False
4194    False
4195    False
4196    False
Length: 4197, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4193    False
4194    False
4195    False
4196    False
4197    False
Length: 4198, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4194    False
4195    False
4196    False
4197    False
4198    False
Length: 4199, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4195    False
4196    False
4197    False
4198    False
4199    False
Length: 4200, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4196    False
4197    False
4198    False
4199    False
4200    False
Length: 4201, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4197    False
4198    False
4199    False
4200    False
4201    False
Length: 4202, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4198    False
4199    False
4200    False
4201    False
4202    False
Length: 4203, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4199    False
4200    False
4201    False
4202    False
4203    False
Length: 4204, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4200    False
4201    False
4202    False
4203    False
4204    False
Length: 4205, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4201    False
4202    False
4203    False
4204    False
4205    False
Length: 4206, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4202    False
4203    False
4204    False
4205    False
4206    False
Length: 4207, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4203    False
4204    False
4205    False
4206    False
4207    False
Length: 4208, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4204    False
4205    False
4206    False
4207    False
4208    False
Length: 4209, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4205    False
4206    False
4207    False
4208    False
4209    False
Length: 4210, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4206    False
4207    False
4208    False
4209    False
4210    False
Length: 4211, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4207    False
4208    False
4209    False
4210    False
4211    False
Length: 4212, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4208    False
4209    False
4210    False
4211    False
4212    False
Length: 4213, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4209    False
4210    False
4211    False
4212    False
4213    False
Length: 4214, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4210    False
4211    False
4212    False
4213    False
4214    False
Length: 4215, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4211    False
4212    False
4213    False
4214    False
4215    False
Length: 4216, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4212    False
4213    False
4214    False
4215    False
4216    False
Length: 4217, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4213    False
4214    False
4215    False
4216    False
4217    False
Length: 4218, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4214    False
4215    False
4216    False
4217    False
4218    False
Length: 4219, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4215    False
4216    False
4217    False
4218    False
4219    False
Length: 4220, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4216    False
4217    False
4218    False
4219    False
4220    False
Length: 4221, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4217    False
4218    False
4219    False
4220    False
4221    False
Length: 4222, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4218    False
4219    False
4220    False
4221    False
4222    False
Length: 4223, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
4219    False
4220    False
4221    False
4222    False
4223    False
Length: 4224, dtype: bool
0       False
1       False
2       False

KeyboardInterrupt:

In [3]:
pd.set_option('display.max_rows', None)
display(pd.read_csv('data/keys/categories.csv'))
pd.set_option('display.max_rows', 50)

,category_name,group_name,subgroup_name,category_ids,object_type_ids
0,Tecnología y electrónica,NaN,FULL_CATEGORY,24200,NaN
1,Tecnología y electrónica,Imagen,FULL_GROUP,24200,10206.0
2,Tecnología y electrónica,Imagen,TV,24200,10414.0
3,Tecnología y electrónica,Imagen,Proyectores,24200,10406.0
4,Tecnología y electrónica,Imagen,Accesorios de televisores y proyectores,24200,10405.0
5,Tecnología y electrónica,Imagen,Otros artículos de imagen,24200,24192.0
6,Tecnología y electrónica,Sonido,FULL_GROUP,24200,24149.0
7,Tecnología y electrónica,Sonido,Auriculares,24200,10395.0
8,Tecnología y electrónica,Sonido,Altavoces,24200,24150.0
9,Tecnología y electrónica,Sonido,Home cinema y barras de sonido,24200,24151.0
10,Tecnología y electrónica,Sonido,Dispositivos de sonido,24200,10205.0
11,Tecnología y electrónica,Sonido,Tocadiscos,24200,10070.0
12,Tecnología y electrónica,Sonido,DJ y audio profesional,24200,24160.0
13,Tecnología y electrónica,Sonido,Otros dispositivos de sonido,24200,24173.0
14,Tecnología y electrónica,Fotografía,FULL_GROUP,24200,10200.0
15,Tecnología y electrónica,Fotografía,Cámaras,24200,10397.0
16,Tecnología y electrónica,Fotografía,Objetivos,24200,10401.0
17,Tecnología y electrónica,Fotografía,Drones,24200,10201.0
18,Tecnología y electrónica,Fotografía,Accesorios de fotografía,24200,24180.0
19,Tecnología y electrónica,Fotografía,Cámaras de vigilancia,24200,10199.0
20,Tecnología y electrónica,Fotografía,Otros articulos de fotografía,24200,24193.0
21,Tecnología y electrónica,Telefonía,FULL_GROUP,24200,24201.0
22,Tecnología y electrónica,Telefonía,Smartphones,24200,9447.0
23,Tecnología y electrónica,Telefonía,Smartwatches y pulsera de actividad,24200,9487.0
24,Tecnología y electrónica,Telefonía,Teléfonos vintage,24200,1017.0
25,Tecnología y electrónica,Telefonía,Telefonos fijos,24200,24102.0
26,Tecnología y electrónica,Telefonía,Otros teléfonos,24200,24103.0
27,Tecnología y electrónica,Telefonía,Accesorios de móviles y smartwatches,24200,9375.0
28,Tecnología y electrónica,Informática,FULL_GROUP,24200,24202.0
29,Tecnología y electrónica,Informática,Portátiles,24200,10310.0
30,Tecnología y electrónica,Informática,Ordenadores de sobremesa,24200,10309.0
31,Tecnología y electrónica,Informática,Realidad Virtual y aumentada,24200,10136.0
32,Tecnología y electrónica,Informática,Tablets,24200,9374.0
33,Tecnología y electrónica,Informática,E-readers,24200,24132.0
34,Tecnología y electrónica,Informática,Periféricos,24200,10134.0
35,Tecnología y electrónica,Informática,Componentes y piezas de ordenador,24200,10304.0
36,Tecnología y electrónica,Informática,Accesorios de informática,24200,24136.0
37,Tecnología y electrónica,Gaming,FULL_GROUP,24200,24203.0
38,Tecnología y electrónica,Gaming,Consolas y accesorios,24200,10087.0
39,Tecnología y electrónica,Gaming,PC gaming y streaming,24200,24115.0
40,Tecnología y electrónica,Gaming,Videojuegos y más,24200,24131.0
41,Deporte y ocio,NaN,FULL_CATEGORY,12579,NaN
42,Deporte y ocio,NaN,Baloncesto,12579,10094.0
43,Deporte y ocio,NaN,Balonmano,12579,10095.0
44,Deporte y ocio,NaN,Estáticas y elípticas,12579,10096.0
45,Deporte y ocio,NaN,"Fitness, running y yoga",12579,10097.0
46,Deporte y ocio,NaN,Fútbol,12579,10098.0
47,Deporte y ocio,NaN,Golf,12579,10099.0
48,Deporte y ocio,NaN,Juegos recreativos y de mesa,12579,10100.0
49,Deporte y ocio,NaN,Manualidades,12579,10101.0
50,Deporte y ocio,NaN,Montaña y esquí,12579,10102.0
51,Deporte y ocio,NaN,Natación y accesorios piscina,12579,10103.0
52,Deporte y ocio,NaN,Otros deportes,12579,10105.0
53,Deporte y ocio,NaN,Patinetes y patinaje,12579,10106.0
54,Deporte y ocio,NaN,Rugby,12579,10107.0
55,Deporte y ocio,NaN,Tenis y pádel,12579,10108.0
56,Deporte y ocio,NaN,Vóley,12579,10109.0
57,Deporte y ocio,NaN,Otros,12579,10104.0
58,Electrodomésticos,NaN,FULL_CATEGORY,13100,NaN
59,Electrodomésticos,NaN,Electrodomésticos de cocina,13100,10111.0
60,Electrodomésticos,NaN,Lavandería y plancha,13100,10112.0
61,Electrodomésticos,NaN,Pequeños electrodomésticos,13100,10113.0
62,Electrodomésticos,NaN,Piezas y recambios,13100,10114.0
63,Electrodomésticos,NaN,Vitrocerámica,13100,10115.0
64,Electrodomésticos,NaN,Otros,13100,10441.0

In [ ]:
def elaborate_item():