In [1]:
ALPHAVANTAGE_API_KEY = 'Q4L3OK0NNB37YQQZ'

import pandas as pd
import numpy as np
import yfinance as yf 
import glob
import requests
import json
import ast
import datetime as dt

pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)

In [12]:
with open('data/ibkr_justetfs_scraped.json', 'r') as f:
    url_data = json.load(f)

    data_list = []
    for url in url_data:
        data = {}
        for prop in url:
            if type(prop) == str:
                data['url'] = prop
            else:
                data.update(prop)
        data_list.append(data)
    df = pd.DataFrame(data_list)

In [10]:
data_list = []
for url in url_data:
    data = {}
    for prop in url:
        if type(prop) == str:
            data['url'] = prop
        else:
            data.update(prop)
    data_list.append(data)
df = pd.DataFrame(data_list)

In [11]:
df

,url,exchanges,historic_dividend,rentabilidad_actual_de_los_dividendos,holdings,sectors,countries,top_10_holdings,num_holdings,índice,foco_de_la_inversión,patrimonio_del_fondo,gastos_corrientes,replicación,estructura_jurídica,riesgo_estratégico,sostenibilidad,divisa_del_fondo,riesgo_de_divisa,volatilidad_1_año_(in_eur),fecha_de_inicio/_de_cotización,política_de_distribución,frecuencia_de_distribución,domicilio_del_fondo,proveedor_de_fondo,categoría,ter,tamaño_del_fondo,participaciones,liquidated,index,category,dividendos_(últimos_12_meses)
0,https://www.justetf.com/es/etf-profile.html?isin=IE000BWITBP9,"[[Euronext París, EUR, 26ID, --, --, -], [XETRA, EUR, D26A, --, --, -], [gettex, EUR, D26A, --, --, -], [Bolsa de Londres, USD, D26A, , , ]]",[],dividendos_(últimos_12_meses),"[[US00287YBV02, 0,84%], [US00774MAV72, 0,74%], [US949746RW34, 0,72%], [US949746SH57, 0,70%], [US594918BR43, 0,68%], [IE00BK8MB266, 0,66%], [US172967KY63, 0,64%], [US61746BDZ67, 0,64%], [US68389XBM65, 0,63%], [US61761J3R84, 0,63%]]","[[Otros, 99,99%]]","[[Otros, 100,00%]]",6.88,486.0,Bloomberg MSCI December 2026 Maturity USD Corporate ESG Screened,"Bonos, USD, Mundial, Deuda corporativa, 0-3, Bonos a vencimiento",EUR 172 m,"0,12% p.a.",Muestreo,ETF,Sólo long,Sí,USD,Sin cobertura de divisas,-,10 de agosto de 2023,Acumulación,-,Irlanda,iShares,"Bonos, Mundial, Deuda corporativa, Bonos a vencimiento, 0-3, Grado de inversión","0,12% p.a.",172 m,486,False,NaN,NaN,NaN
1,https://www.justetf.com/es/etf-profile.html?isin=IE0000UJ3480,"[[Euronext París, EUR, 28ID, --, --, -], [XETRA, EUR, CBU5, --, --, -], [gettex, EUR, CBU5, --, --, -], [Bolsa de Londres, USD, D28A, , , ]]",[],dividendos_(últimos_12_meses),"[[US92343VER15, 1,20%], [US716973AC67, 1,16%], [US20030NCT63, 1,12%], [US031162DP23, 1,07%], [US125523AH38, 1,06%], [US00774MAW55, 0,96%], [US92343VGH15, 0,81%], [US852060AD48, 0,80%], [US22550L2M24, 0,79%], [US17325FBB31, 0,72%]]","[[Otros, 99,99%]]","[[Otros, 100,00%]]",9.69,411.0,Bloomberg MSCI December 2028 Maturity USD Corporate ESG Screened,"Bonos, USD, Mundial, Deuda corporativa, 3-5, Bonos a vencimiento",EUR 320 m,"0,12% p.a.",Muestreo,ETF,Sólo long,Sí,USD,Sin cobertura de divisas,-,10 de agosto de 2023,Acumulación,-,Irlanda,iShares,"Bonos, Mundial, Deuda corporativa, Bonos a vencimiento, 3-5, Grado de inversión","0,12% p.a.",320 m,411,False,NaN,NaN,NaN
2,https://www.justetf.com/es/etf-profile.html?isin=IE00BKT6ZG93,[],[],dividendos_(últimos_12_meses),[],[],[],NaN,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN
3,https://www.justetf.com/es/etf-profile.html?isin=IE00B42YS929,"[[gettex, EUR, 2B73, --, --, -], [Bolsa de Londres, GBX, IGWD, --, --, -], [Bolsa de Londres, GBP, -, IGWD LNINAVGWDG, IGWD.LIGWDGINAV.DE, ]]",[],dividendos_(últimos_12_meses),"[[Microsoft Corp., 4,43%], [Apple, 4,25%], [NVIDIA Corp., 4,13%], [Amazon.com, Inc., 2,53%], [Meta Platforms, 1,57%], [Alphabet, Inc. A, 1,54%], [Alphabet, Inc. C, 1,36%], [Eli Lilly & Co., 0,99%], [Broadcom Inc., 0,92%], [JPMorgan Chase & Co., 0,87%]]","[[Tecnología, 25,99%], [Servicios financieros, 13,01%], [Salud, 10,54%], [Consumidor discrecional, 10,22%], [Otros, 40,24%]]","[[Estados Unidos, 66,76%], [Japón, 5,73%], [Reino Unido, 3,68%], [Francia, 2,81%], [Otros, 21,02%]]",22.59,1466.0,MSCI World (GBP Hedged),"Acciones, Mundial",EUR 348 m,"0,55% p.a.",Muestreo,ETF,Sólo long,No,GBP,Cobertura de divisas,"10,00%",30 de septiembre de 2010,Acumulación,-,Irlanda,iShares,"Acciones, Mundial","0,55% p.a.",348 m,1.466,False,NaN,NaN,NaN
4,https://www.justetf.com/es/etf-profile.html?isin=IE00BK5C1C97,[],[],dividendos_(últimos_12_meses),[],[],[],NaN,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2252,https://www.justetf.com/es/etf-profile.html?isin=CH1199067674,"[[Euronext Amsterdam, USD, CBTC, --, --, -], [Euronext París, EUR, CBTC, --, --, -], [Bolsa suiza SIX, USD, CBTC, --, --, -], [XETRA, EUR, 21BC, --, --, -], [gettex, EUR, 21BC, --, --, -], [Bolsa de Londres, GBP, CBTC, --, --, -], [Bolsa de Londres, USD, CBTU, --, --, -]]",[],dividendos_(últimos_12_meses),[],[],[],NaN,NaN,Bitcoin,Criptomonedas,EUR 110 m,"0,21% p.a.",Replicación física perfecta,ETN,Sólo long,No,USD,Sin cobertura de divisas,"43,30%",29 de junio de 2022,Acumulación,-,Suiza,21Shares,NaN,"0,21% p.a.",110 m,NaN,False,NaN,NaN,NaN
2253,https://www.justetf.com/es/etf-profile.html?isin=CH0496484640,"[[Bolsa suiza SIX, USD, ABBA, --, --, -], [gettex, EUR, 21XA, --, --, -], [Bolsa de Stuttgart, EUR, 21XA, --, --, -], [Bolsa suiza SIX, CHF, ABBA, --, --, -]]",[],dividendos_(últimos_12_meses),[],[],[],NaN,NaN,21Shares Bitcoin Suisse,Criptomonedas,EUR 37 m,"2,50% p.a.",Replicación física perfecta,ETN,Sólo long,No,USD,Sin cobertura de divisas,"42,23%",4 de octubre de 2019,Acumulación,-,Suiza,21Shares,NaN,"2,50% p.a.",37 m,NaN,False,NaN,NaN,NaN
2254,https://www.justetf.com/es/etf-profile.html?isin=CH0496454155,"[[Euronext Amsterdam, USD, BNBA, --, --, -], [Euronext París, EUR, BNBA, --, --, -], [Bolsa suiza SIX, USD, ABNB, --, --, -], [XETRA, EUR, 21XJ, --, --, -], [gettex, EUR, 21XJ, --, --, -]]",[],dividendos_(últimos_12_meses),[],[],[],NaN,NaN,Binance Coin (BNB),Criptomonedas,EUR 650 m,"2,50% p.a.",Replicación física perfecta,ETN,Sólo long,No,USD,Sin cobertura de divisas,"54,69%",15 de octubre de 2019,Acumulación,-,Suiza,21Shares,NaN,"2,50% p.a.",650 m,NaN,False,NaN,NaN,NaN
2255,https://www.justetf.com/es/etf-profile.html?isin=CH1100083471,"[[Euronext Amsterdam, USD, ALINK, --, --, -], [Euronext París, EUR, ALINK, --, --, -], [XETRA, EUR, 21XL, --, --, -], [gettex, EUR, 21XL, --, --, -]]",[],dividendos_(últimos_12_meses),[],[],[],NaN,NaN,Chainlink,Criptomonedas,EUR 13 m,"2,50% p.a.",Replicación física perfecta,ETN,Sólo long,No,USD,Sin cobertura de divisas,"78,96%",31 de enero de 2022,Acumulación,-,Suiza,21Shares,NaN,"2,50% p.a.",13 m,NaN,False,NaN,NaN,NaN
2256,https://www.justetf.com/es/etf-profile.html?isin=CH0454664043,"[[Euronext Amsterdam, USD, AXRP, --, --, -], [Euronext París, EUR, AXRP, --, --, -], [Bolsa suiza SIX, USD, AXRP, --, --, -], [XETRA, EUR, 21XP, --, --, -], [gettex, EUR, 21XP, --, --, -], [Bolsa de Stuttgart, EUR, 21XX, --, --, -], [Bolsa suiza SIX, CHF, AXRP, --, --, -]]",[],dividendos_(últimos_12_meses),[],[],[],NaN,NaN,Ripple (XRP),Criptomonedas,EUR 50 m,"2,50% p.a.",Replicación física perfecta,ETN,Sólo long,No,USD,Sin cobertura de divisas,"76,34%",21 de junio de 2019,Acumulación,-,Suiza,21Shares,NaN,"2,50% p.a.",50 m,NaN,False,NaN,NaN,NaN

In [ ]:
def expand_sectors(row):
    if row == []:
        return {}
    elif row == None:
        return {}
    else:
        return dict((f'{col}_{x[0]}', x[1]) for x in row)

list_columns = ['sectors', 'countries', 'historic_dividend',]

for col in list_columns:
    df[col] = df[col].apply(expand_sectors)
    temp_df = df[col].apply(pd.Series)
    df = df.drop([col], axis=1)

    df = pd.concat([df, temp_df], axis=1)

In [ ]:
df['current_dividend_yield'] = df['current_dividend_yield'].replace('dividends_(last_12_months)', np.nan)
df['holdings'] = df['holdings'].replace([], np.nan)
df = df.drop(['num_holdings'], axis=1)
for col in df.columns:
    df[col] = df[col].replace('-', np.nan)

non_numeric = ['url', 'index',	'investment_focus', 'replication',	'legal_structure','strategy_risk',	'sustainability',	'fund_currency',	'currency_risk', 'inception/_listing_date',	'distribution_policy',	'distribution_frequency',	'fund_domicile',	'fund_provider', 'category', 'liquidated', 'isin']

numeric = [item for item in df.columns.to_list() if item not in non_numeric]

for col in numeric:
    df[col] = df[col].apply(lambda x: x.replace(',', '') if isinstance(x, str) else x)
    df[col] = df[col].apply(lambda x: x.replace('+', '') if isinstance(x, str) else x)
    df[col] = df[col].apply(lambda x: x.replace(' m', '000000') if isinstance(x, str) else x)
    df[col] = df[col].apply(lambda x: x.replace(' p.a.', '') if isinstance(x, str) else x)
    df[col] = df[col].apply(lambda x: x.replace('EUR ', '') if isinstance(x, str) else x)
    # df[col] = df[col].apply(ast.literal_eval)

non_percentage = ['return_per_risk_1_year',	'return_per_risk_3_years',	'return_per_risk_5_years', 'dividends_(last_12_months)', 'holdings',	'top_10_holdings', 'fund_size']

percentages = [item for item in numeric if item not in non_percentage]

for col in percentages:
    if df[col].dtype != 'float':
        df[col] = df[col].str.rstrip('%').astype('float') / 100.0

In [ ]:
def expand2(row):
    if row is None or isinstance(row, float):
        return {}
    else:
        return dict((f'{col}_{x}', True) for x in row)

string_lists = ['investment_focus', 'category']

for col in string_lists:
    df[col] = df[col].apply(lambda x: x.split(', ') if isinstance(x, str) else x)
    df[col] = df[col].apply(expand2)
    temp_df = df[col].apply(pd.Series)
    df = df.drop([col], axis=1)

    df = pd.concat([df, temp_df], axis=1)

In [ ]:
df = df[df['liquidated'] == False].sort_values(by="ter")
df = df[df['replication'] == 'Full replication']
eur = df[df['fund_currency'] == 'EUR']
eur = eur.dropna(axis=1, how='all')

In [ ]:
bonds = eur[eur['category_Bonds'] == True].dropna(axis=1, how='all')
bonds[bonds['category_World'] == True]

,url,volatility_1_year,volatility_3_years,volatility_5_years,return_per_risk_1_year,return_per_risk_3_years,return_per_risk_5_years,maximum_drawdown_1_year,maximum_drawdown_3_years,maximum_drawdown_5_years,maximum_drawdown_since_inception,current_dividend_yield,dividends_(last_12_months),ytd,1_month,3_months,6_months,1_year,3_years,5_years,since_inception_(max),2023,2022,2021,2020,holdings,top_10_holdings,index,fund_size,total_expense_ratio,replication,legal_structure,strategy_risk,sustainability,fund_currency,currency_risk,volatility_1_year_(in_eur),inception/_listing_date,distribution_policy,distribution_frequency,fund_domicile,fund_provider,ter,liquidated,isin,sectors_Other,countries_Germany,countries_France,countries_Italy,countries_Spain,countries_Other,countries_United States,countries_Ireland,countries_Japan,countries_United Kingdom,countries_Canada,countries_Netherlands,countries_China,countries_Singapore,countries_New Zealand,countries_Finland,countries_Switzerland,countries_Austria,countries_Luxembourg,countries_Belgium,countries_Indonesia,countries_Saudi Arabia,countries_Sweden,countries_Qatar,countries_Cayman Islands,countries_Portugal,countries_United Arab Emirates,countries_Slovakia,countries_Argentina,historic_dividend_1 Year,historic_dividend_2023,historic_dividend_2022,historic_dividend_2021,historic_dividend_2020,historic_dividend_2019,investment_focus_Europe,investment_focus_United States,investment_focus_Social/Environmental,investment_focus_World,investment_focus_Bonds,investment_focus_Aggregate,investment_focus_3-5,investment_focus_7-10,investment_focus_China,investment_focus_CNY,investment_focus_Government,investment_focus_All maturities,investment_focus_USD,investment_focus_Inflation-Linked,investment_focus_10+,investment_focus_EUR,investment_focus_Germany,investment_focus_Corporate,investment_focus_Convertible Bonds,investment_focus_0-3,investment_focus_5-7,investment_focus_Covered Bonds,investment_focus_Maturity bonds,category_Europe,category_United States,category_Social/Environmental,category_World,category_China,category_Bonds,category_Government,category_All maturities,category_Investment Grade,category_Inflation-Linked,category_10+,category_Aggregate,category_3-5,category_Mixed Ratings,category_Germany,category_Corporate,category_Convertible Bonds,category_7-10,category_AAA Rating,category_Sub Investment Grade,category_0-3,category_5-7,category_Covered Bonds,category_Maturity bonds
1111,https://www.justetf.com/en/etf-profile.html?isin=NL0009690247,0.0445,0.0516,0.0462,1.02,-0.54,-0.24,-0.0265,-0.1705,-0.1708,-0.1708,0.0066,0.11,-0.0118,-0.0066,-0.0060,-0.0042,0.0456,-0.0814,-0.0533,0.2697,0.0863,-0.1378,-0.0148,0.0239,40,0.3575,iBoxx® SD-KPI EUR Liquid Corporates,35000000,0.0015,Full replication,ETF,Long-only,Yes,EUR,Currency unhedged,0.0445,14 April 2011,Distributing,Quarterly,Netherlands,VanEck,0.0015,False,NL0009690247,1.0000,0.1734,NaN,NaN,NaN,0.5060,0.1444,NaN,NaN,NaN,NaN,0.0593,NaN,NaN,NaN,NaN,NaN,NaN,0.1169,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0011,0.0019,0.0022,0.0014,0.0019,NaN,NaN,NaN,True,True,True,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,True,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,True,NaN,True,True,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
732,https://www.justetf.com/en/etf-profile.html?isin=LU2533812728,0.0522,NaN,NaN,0.84,NaN,NaN,-0.0314,NaN,NaN,-0.0353,0.0302,0.30,-0.0066,0.0061,0.0032,0.0012,0.0442,NaN,NaN,0.0315,NaN,NaN,NaN,NaN,890,0.0413,Bloomberg MSCI Euro Aggregate ex Fossil Fuel SRI Select,18000000,0.0015,Full replication,ETF,Long-only,Yes,EUR,Currency unhedged,0.0522,2 February 2023,Distributing,Annually,Luxembourg,BNP Paribas Easy,0.0015,False,LU2533812728,1.0000,NaN,NaN,NaN,NaN,1.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,True,True,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,True,NaN,True,True,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1041,https://www.justetf.com/en/etf-profile.html?isin=LU2533812991,0.0521,NaN,NaN,0.84,NaN,NaN,-0.0314,NaN,NaN,-0.0353,NaN,NaN,-0.0068,0.0059,0.0029,0.0010,0.0439,NaN,NaN,0.0313,NaN,NaN,NaN,NaN,890,0.0413,Bloomberg MSCI Euro Aggregate ex Fossil Fuel SRI Select,148000000,0.0015,Full replication,ETF,Long-only,Yes,EUR,Currency unhedged,0.0521,2 February 2023,Accumulating,NaN,Luxembourg,BNP Paribas Easy,0.0015,False,LU2533812991,1.0000,NaN,NaN,NaN,NaN,1.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,True,True,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,True,NaN,True,True,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1042,https://www.justetf.com/en/etf-profile.html?isin=IE00BNDS1P30,0.0884,0.0992,NaN,0.55,-0.36,NaN,-0.0437,-0.2082,NaN,-0.2082,NaN,NaN,0.0022,0.0112,0.0157,0.0000,0.0486,-0.1047,NaN,-0.0958,0.0660,-0.1637,NaN,NaN,4126,0.0133,Bloomberg MSCI Global Corporate Float-Adjusted Liquid Bond Screened (EUR Hedged),278000000,0.0015,Full replication,ETF,Long-only,Yes,EUR,Currency hedged,0.0884,20 May 2021,Accumulating,NaN,Ireland,Vanguard,0.0015,False,IE00BNDS1P30,0.8451,NaN,0.0387,NaN,NaN,0.4554,0.4075,NaN,NaN,0.0662,NaN,0.0322,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,True,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,True,NaN,True,True,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1019,https://www.justetf.com/en/etf-profile.html?isin=IE00BNDS1Q47,0.0913,0.1030,NaN,0.49,-0.36,NaN,-0.0444,-0.2077,NaN,-0.2077,0.0435,0.18,-0.0006,0.0068,0.0127,-0.0030,0.0449,-0.1071,NaN,-0.0982,0.0638,-0.1595,NaN,NaN,4126,0.0133,Bloomberg MSCI Global Corporate Float-Adjusted Liquid Bond Screened (EUR Hedged),294000000,0.0015,Full replication,ETF,Long-only,Yes,EUR,Currency hedged,0.0913,20 May 2021,Distributing,Monthly,Ireland,Vanguard,0.0015,False,IE00BNDS1Q47,0.8451,NaN,0.0384,NaN,NaN,0.4545,0.4092,NaN,NaN,0.0660,NaN,0.0319,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0018,0.0017,0.0010,NaN,NaN,NaN,NaN,NaN,True,True,True,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,True,NaN,True,True,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1776,https://www.justetf.com/en/etf-profile.html?isin=IE000STIHQB2,0.0039,NaN,NaN,11.13,NaN,NaN,-0.0004,NaN,NaN,-0.0012,NaN,NaN,0.0197,0.0038,0.0100,0.0221,0.0431,NaN,NaN,0.0468,NaN,NaN,NaN,NaN,94,0.5438,Franklin Euro Short Maturity,46000000,0.0015,Full replication,ETF,Actively managed,Yes,EUR,Currency unhedged,0.0039,24 April 2023,Accumulating,NaN,Ireland,Franklin Templeton,0.0015,False,IE000STIHQB2,1.0000,NaN,NaN,NaN,NaN,1.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,True,True,NaN,True,NaN,NaN,NaN,NaN,NaN,True,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN
875,https://www.justetf.com/en/etf-profile.html?isin=IE00BD9MMF62,0.0027,0.0029,0.0030,15.12,4.88,2.62,-0.0003,-0.0124,-0.0165,-0.0167,NaN,NaN,0.0170,0.0037,0.0096,0.0190,0.0412,0.0425,0.0399,0.0380,0.0334,-0.0048,-0.0038,-0.0019,164,0.1469,JP Morgan EUR Ultra-Short Income,829000000,0.0018,Full replication,ETF,Actively managed,No,EUR,Currency unhedged,0.0027,6 June 2018,Accumulating,NaN,Ireland,J.P. Morgan,0.0018,False,IE00BD9MMF62,0.9469,NaN,0.0264,NaN,NaN,0.8138,0.0868,NaN,NaN,0.0433,0.0297,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,True,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,True,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN
395,https://www.justetf.com/en/etf-profile.html?isin=LU2297533809,0.1048,0.1127,NaN,0.35,-0.40,NaN,-0.0669,-0.2318,NaN,-0.2318,0.0393,1.57,-0.0040,0.0129,0.0166,-0.0092,0.0371,-0.1307,NaN,-0.1078,0.0536,-0.1765,NaN,NaN,4560,0.0128,Bloomberg MSCI US Corporate SRI (EUR Hedged),310000000,0.0018,Full replication,ETF,Long-only,Yes,EUR,Currency hedged,0.1048,3 March 2021,Distributing,Annually,Luxembourg,Amundi ETF,0.0018,False,LU2297533809,1.0000,NaN,NaN,NaN,NaN,0.3019,0.6240,NaN,0.0193,0.0344,0.0204,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0157,0.0157,0.0162,NaN,NaN,NaN,NaN,NaN,True,True,True,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,True,NaN,True,True,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1289,https://www.justetf.com/en/etf-profile.html?isin=IE0006LBEDV2,0.0377,NaN,NaN,1.48,NaN,NaN,-0.0158,NaN,NaN,-0.0880,0.0337,0.17,-0.0014,-0.0020,0.0000,0.0065,0.0558,NaN,NaN,0.0565,0.0765,NaN,NaN,NaN,162,0.1714,Invesco EUR Corporate Bond ESG Multi-Factor,21000000,0.0019,Full replication,ETF,Actively managed,Yes,EUR,Currency unhedged,0.0377,22 June 2022,Distributing,Quarterly,Ireland,Invesco,0.0019,False,IE0006LBEDV2,0.9959,NaN,0.1780,NaN,0.0705,0.5311,0.1261,NaN,NaN,NaN,NaN,0.0943,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0017,0.0016,NaN,NaN,NaN,NaN,NaN,NaN,True,True,True,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,True,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,True,NaN,True,True,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2002,https://www.justetf.com/en/etf-profile.html?isin=IE0000J0F3C5,0.1053,NaN,NaN,0.36,NaN,NaN,-0.0697,NaN,NaN,-0.2334,NaN,NaN,-0.0025,0.0136,0.0177,-0.0085,0.0378,NaN,NaN,-0.1466,0.0601,-0.1833,NaN,NaN,313,0.1297,JP Morgan USD Corporate Bond Research Enhanced Index (ESG) (EUR Hedged),4000000,0.0019,Full replication,ETF,Actively managed,Yes,EUR,Currency hedged,0.1053,9 November 2021,Accumulating,NaN,Ireland,J.P. Morgan,0.0019,False,IE0000J0F3C5,0.9895,NaN,NaN,NaN,NaN,0.3250,0.6127,0.0137,0.0242,0.0244,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,True,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,True,NaN,True,True,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1520,https://www.justetf.com/en/etf-profile.html?isin=IE00021E4FE3,0.0391,NaN,NaN,1.68,NaN,NaN,-0.0158,NaN,NaN,-0.0875,NaN,NaN,0.0076,0.0076,0.0095,0.0152,0.0660,NaN,NaN,0.0660,0.0774,NaN,NaN,NaN,162,0.1714,Invesco EUR Corporate Bond ESG Multi-Factor,4000000,0.0019,Full replication,ETF,Actively managed,Yes,EUR,Currency unhedged,0.0391,22 June 2022,Accumulating,NaN,Ireland,Invesco,0.0019,False,IE00021E4FE3,0.9959,NaN,0.1731,NaN,0.0704,0.5405,0.1217,NaN,NaN,NaN,NaN,0.0943,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,True,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,True,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,True,NaN,True,True,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1166,https://www.justetf.com/en/etf-profile.html?isin=IE000JBB8CR7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.0169,NaN,NaN,0.0066,0.0066,0.0075,0.0142,NaN,NaN,NaN,0.0710,NaN,NaN,NaN,NaN,[],NaN,AXA IM Euro Credit PAB,190000000,0.0020,Full replication,ETF,Actively managed,Yes,EUR,Currency unhedged,NaN,11 July 2023,Accumulating,NaN,Ireland,AXA IM,0.0020,False,IE000JBB8CR7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,True,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,True,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,True,NaN,True,True,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,https://www.justetf.com/en/etf-profile.html?isin=LU2446383338,0.0323,NaN,NaN,1.88,NaN,NaN,-0.0130,NaN,NaN,-0.0281,NaN,NaN,0.0056,0.0056,0.0075,0.0122,0.0609,NaN,NaN,0.0651,0.0708,NaN,NaN,NaN,498,0.0552,Bloomberg MSCI 3-5Y Euro Corporate SRI Sustainable Select Ex Fossil Fuel PAB,6000000,0.0020,Full replication,ETF,Long-only,Yes,EUR,Currency unhedged,0.0323,27 October 2022,Accumulating,NaN,Luxembourg,BNP Paribas Easy,0.0020,False,LU2446383338,0.9998,NaN,NaN,NaN,NaN,1.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,True,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,True,NaN,NaN,True,NaN,NaN,NaN,True,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1654,https://www.justetf.com/en/etf-profile.html?isin=LU1953136287,0.0425,NaN,NaN,1.52,NaN,NaN,-0.0190,NaN,NaN,-0.1509,0.0363,0.33,0.0046,0.0066,0.0089,0.0132,0.0647,NaN,NaN,-0.0421,0.0731,NaN,NaN,NaN,1737,0.0174,Bloomberg MSCI Euro Corporate SRI Sustainable Select Ex Fossil Fuel PAB,127000000,0.0020,Full replication,ETF,Long-only,Yes,EUR,Currency unhedged,0.0425,10 February 2022,Distributing,Annually,Luxembourg,BNP Paribas Easy,0.0020,False,LU1953136287,0.9991,0.0647,0.1563,NaN,NaN,0.5775,0.1213,NaN,NaN,NaN,NaN,0.0802,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0033,0.0010,NaN,NaN,NaN,NaN,NaN,NaN,True,True,True,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,True,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,True,NaN,True,True,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
467,https://www.justetf.com/en/etf-profile.html?isin=DE000ETFL375,0.0381,0.0455,0.0413,1.63,-0.56,-0.24,-0.0171,-0.1701,-0.1701,-0.1701,0.0276,2.76,0.0044,0.0043,0.0065,0.0114,0.0623,-0.0748,-0.0485,0.3240,0.0765,-0.1402,-0.0106,0.0180,75,0.1982,iBoxx® EUR Liquid Corporates Diversified,341000000,0.0020,Full replication,ETF,Long-only,No,EUR,Currency unhedged,0.0381,17 February 2010,Distributing,Quarterly,Germany,Deka ETFs,0.0020,False,DE000ETFL375,0.9984,0.0467,0.2092,NaN,0.0406,0.6682,NaN,NaN,NaN,NaN,NaN,0.0353,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0276,0.0308,0.0073,0.0078,0.0080,NaN,NaN,NaN,NaN,True,True,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,True,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,True,NaN,True,True,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
577,https://www.justetf.com/en/etf-profile.html?isin=DE000ETFL383,0.0464,0.0577,0.0512,1.22,-0.59,-0.24,-0.0232,-0.1968,-0.1968,-0.1968,0.0225,2.19,0.0006,0.0090,0.0102,0.0084,0.0569,-0.0982,-0.0611,0.2889,0.0798,-0.1602,-0.0138,0.0281,40,0.3243,iBoxx® EUR Liquid Non-Financials Diversified,136000000,0.0020,Full replication,ETF,Long-only,No,EUR,Currency unhedged,0.0464,3 March 2011,Distributing,Quarterly,Germany,Deka ETFs,0.0020,False,DE000ETFL383,0.9990,0.0582,0.2647,NaN,0.0481,0.5134,NaN,NaN,NaN,NaN,NaN,0.1156,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0219,0.0230,0.0111,0.0103,0.0104,NaN,NaN,NaN,NaN,True,True,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,True,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,True,NaN,True,True,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1895,https://www.justetf.com/en/etf-profile.html?isin=LU1859444769,0.0414,0.0518,0.0474,1.55,-0.59,-0.23,-0.0191,-0.1927,-0.1927,-0.1927,NaN,NaN,0.0051,0.0071,0.0081,0.0133,0.0645,-0.0884,-0.0535,-0.0198,0.0730,-0.1476,-0.0164,0.0282,1737,0.0174,Bloomberg MSCI Euro Corporate SRI Sustainable Select Ex Fossil Fuel PAB,1006000000,0.0020,Full replication,ETF,Long-only,Yes,EUR,Currency unhedged,0.0414,15 January 2019,Accumulating,NaN,Luxembourg,BNP Paribas Easy,0.0020,False,LU1859444769,0.9991,0.0647,0.1563,NaN,NaN,0.5775,0.1213,NaN,NaN,NaN,NaN,0.0802,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,True,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,True,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,True,NaN,True,True,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
612,https://www.justetf.com/en/etf-profile.html?isin=IE000L0X6L81,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.0228,NaN,NaN,NaN,0.0087,0.0059,NaN,NaN,NaN,NaN,0.0146,NaN,NaN,NaN,NaN,[],NaN,Solactive Global Green Bond Select (EUR Hedged),51000000,0.0022,Full replication,ETF,Long-only,Yes,EUR,Currency hedged,NaN,13 February 2024,Distributing,Semi annually,Ireland,Goldman Sachs,0.0022,False,IE000L0X6L81,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,True,True,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,True,NaN,True,True,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1286,https://www.justetf.com/en/etf-profile.html?isin=IE000SYQFJV2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.0203,NaN,NaN,NaN,0.0056,-0.0006,NaN,NaN,NaN,NaN,0.0092,NaN,NaN,NaN,NaN,[],NaN,Solactive Global Green Bond Select,0000000,0.0022,Full replication,ETF,Long-only,Yes,EUR,Currency unhedged,NaN,13 February 2024,Distributing,Semi annually,Ireland,Goldman Sachs,0.0022,False,IE000SYQFJV2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,True,True,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,True,NaN,True,True,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1400,https://www.justetf.com/en/etf-profile.html?isin=LU2244386053,0.0277,0.0435,NaN,3.17,-0.01,NaN,-0.0148,-0.1665,NaN,-0.1665,NaN,NaN,0.0191,0.0030,0.0070,0.0264,0.0882,-0.0010,NaN,0.0110,0.1009,-0.1060,NaN,NaN,335,0.0633,Bloomberg MSCI Euro High Yield SRI Sustainable Ex Fossil Fuel,303000000,0.0025,Full replication,ETF,Long-only,Yes,EUR,Currency unhedged,0.0277,18 February 2021,Accumulating,NaN,Luxembourg,BNP Paribas Easy,0.0025,False,LU2244386053,0.9998,NaN,0.0885,0.1733,NaN,0.5396,0.1324,NaN,NaN,NaN,NaN,0.0662,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,True,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,True,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,True,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN
1389,https://www.justetf.com/en/etf-profile.html?isin=LU2244386137,0.0281,0.0437,NaN,3.13,-0.01,NaN,-0.0147,-0.1656,NaN,-0.1656,0.0631,0.56,0.0190,0.0034,0.0070,0.0267,0.0882,-0.0008,NaN,0.0122,0.1004,-0.1053,NaN,NaN,335,0.0633,Bloomberg MSCI Euro High Yield SRI Sustainable Ex Fossil Fuel,3000000,0.0025,Full replication,ETF,Long-only,Yes,EUR,Currency unhedged,0.0281,18 February 2021,Distributing,Annually,Luxembourg,BNP Paribas Easy,0.0025,False,LU2244386137,0.9998,NaN,0.0885,0.1733,NaN,0.5397,0.1323,NaN,NaN,NaN,NaN,0.0662,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0056,0.0028,0.0034,NaN,NaN,NaN,NaN,NaN,True,True,True,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,True,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,True,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN
1990,https://www.justetf.com/en/etf-profile.html?isin=LU2365458814,0.0631,NaN,NaN,0.73,NaN,NaN,-0.0403,NaN,NaN,-0.2637,NaN,NaN,-0.0149,0.0038,-0.0013,-0.0063,0.0461,NaN,NaN,-0.2068,0.0732,-0.2329,NaN,NaN,568,0.1675,J.P. Morgan ESG Green Social & Sustainability IG EUR Bond,143000000,0.0025,Full replication,ETF,Long-only,Yes,EUR,Currency unhedged,0.0631,10 December 2021,Accumulating,NaN,Luxembourg,BNP Paribas Easy,0.0025,False,LU2365458814,0.9997,0.0686,0.1639,NaN,NaN,0.6230,NaN,NaN,NaN,NaN,NaN,0.0747,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0698,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,True,True,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,True,NaN,True,True,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
world = eur[eur['investment_focus_World'] == True].dropna(axis=1, how='all')
world[world['sectors_Other'] == True]

,url,volatility_1_year,volatility_3_years,volatility_5_years,return_per_risk_1_year,return_per_risk_3_years,return_per_risk_5_years,maximum_drawdown_1_year,maximum_drawdown_3_years,maximum_drawdown_5_years,maximum_drawdown_since_inception,current_dividend_yield,dividends_(last_12_months),ytd,1_month,3_months,6_months,1_year,3_years,5_years,since_inception_(max),2023,2022,2021,2020,holdings,top_10_holdings,index,fund_size,total_expense_ratio,replication,legal_structure,strategy_risk,sustainability,fund_currency,currency_risk,volatility_1_year_(in_eur),inception/_listing_date,distribution_policy,distribution_frequency,fund_domicile,fund_provider,ter,liquidated,isin,sectors_Industrials,sectors_Financials,sectors_Basic Materials,sectors_Technology,sectors_Other,sectors_Health Care,sectors_Consumer Discretionary,sectors_Utilities,sectors_Consumer Staples,sectors_Real Estate,sectors_Telecommunication,sectors_Energy,countries_Germany,countries_France,countries_Italy,countries_Spain,countries_Other,countries_United States,countries_Ireland,countries_Japan,countries_United Kingdom,countries_Canada,countries_Netherlands,countries_China,countries_Hong Kong,countries_Australia,countries_Singapore,countries_New Zealand,countries_Finland,countries_Switzerland,countries_Taiwan,countries_Denmark,countries_Israel,countries_Luxembourg,countries_Belgium,countries_Cayman Islands,countries_Argentina,historic_dividend_1 Year,historic_dividend_2023,historic_dividend_2022,historic_dividend_2021,historic_dividend_2020,investment_focus_Equity,investment_focus_Social/Environmental,investment_focus_World,investment_focus_Bonds,investment_focus_Aggregate,investment_focus_3-5,investment_focus_Government,investment_focus_All maturities,investment_focus_Multi-Factor Strategy,investment_focus_Fundamental/Quality,investment_focus_Dividend,investment_focus_USD,investment_focus_Technology,investment_focus_EUR,investment_focus_Corporate,investment_focus_Convertible Bonds,investment_focus_Agribusiness,investment_focus_Infrastructure,investment_focus_0-3,investment_focus_Utilities,investment_focus_Real Estate,investment_focus_Equal Weighted,investment_focus_Health Care,category_Equity,category_Social/Environmental,category_World,category_Bonds,category_Government,category_All maturities,category_Investment Grade,category_Multi-Factor Strategy,category_Fundamental/Quality,category_Climate Change,category_Dividend,category_Aggregate,category_3-5,category_Mixed Ratings,category_Technology,category_Corporate,category_Gender Equality,category_Convertible Bonds,category_Sub Investment Grade,category_Future of Food,category_Agribusiness,category_Infrastructure,category_0-3,category_Clean Energy,category_Utilities,category_Cybersecurity,category_Real Estate,category_Water,category_Hydrogen,category_Health Care,category_Circular Economy,category_Equal Weighted,category_Multi-Asset Strategy,category_Semiconductors
1111,https://www.justetf.com/en/etf-profile.html?isin=NL0009690247,0.0445,0.0516,0.0462,1.02,-0.54,-0.24,-0.0265,-0.1705,-0.1708,-0.1708,0.0066,0.11,-0.0118,-0.0066,-0.0060,-0.0042,0.0456,-0.0814,-0.0533,0.2697,0.0863,-0.1378,-0.0148,0.0239,40,0.3575,iBoxx® SD-KPI EUR Liquid Corporates,35000000,0.0015,Full replication,ETF,Long-only,Yes,EUR,Currency unhedged,0.0445,14 April 2011,Distributing,Quarterly,Netherlands,VanEck,0.0015,False,NL0009690247,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.1734,NaN,NaN,NaN,0.5060,0.1444,NaN,NaN,NaN,NaN,0.0593,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.1169,NaN,NaN,NaN,0.0011,0.0019,0.0022,0.0014,0.0019,NaN,True,True,True,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,True,NaN,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
732,https://www.justetf.com/en/etf-profile.html?isin=LU2533812728,0.0522,NaN,NaN,0.84,NaN,NaN,-0.0314,NaN,NaN,-0.0353,0.0302,0.30,-0.0066,0.0061,0.0032,0.0012,0.0442,NaN,NaN,0.0315,NaN,NaN,NaN,NaN,890,0.0413,Bloomberg MSCI Euro Aggregate ex Fossil Fuel SRI Select,18000000,0.0015,Full replication,ETF,Long-only,Yes,EUR,Currency unhedged,0.0522,2 February 2023,Distributing,Annually,Luxembourg,BNP Paribas Easy,0.0015,False,LU2533812728,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0030,NaN,NaN,NaN,NaN,NaN,True,True,True,True,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,True,NaN,True,True,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1041,https://www.justetf.com/en/etf-profile.html?isin=LU2533812991,0.0521,NaN,NaN,0.84,NaN,NaN,-0.0314,NaN,NaN,-0.0353,NaN,NaN,-0.0068,0.0059,0.0029,0.0010,0.0439,NaN,NaN,0.0313,NaN,NaN,NaN,NaN,890,0.0413,Bloomberg MSCI Euro Aggregate ex Fossil Fuel SRI Select,148000000,0.0015,Full replication,ETF,Long-only,Yes,EUR,Currency unhedged,0.0521,2 February 2023,Accumulating,NaN,Luxembourg,BNP Paribas Easy,0.0015,False,LU2533812991,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,True,True,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,True,NaN,True,True,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1776,https://www.justetf.com/en/etf-profile.html?isin=IE000STIHQB2,0.0039,NaN,NaN,11.13,NaN,NaN,-0.0004,NaN,NaN,-0.0012,NaN,NaN,0.0197,0.0038,0.0100,0.0221,0.0431,NaN,NaN,0.0468,NaN,NaN,NaN,NaN,94,0.5438,Franklin Euro Short Maturity,46000000,0.0015,Full replication,ETF,Actively managed,Yes,EUR,Currency unhedged,0.0039,24 April 2023,Accumulating,NaN,Ireland,Franklin Templeton,0.0015,False,IE000STIHQB2,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,True,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
395,https://www.justetf.com/en/etf-profile.html?isin=LU2297533809,0.1048,0.1127,NaN,0.35,-0.40,NaN,-0.0669,-0.2318,NaN,-0.2318,0.0393,1.57,-0.0040,0.0129,0.0166,-0.0092,0.0371,-0.1307,NaN,-0.1078,0.0536,-0.1765,NaN,NaN,4560,0.0128,Bloomberg MSCI US Corporate SRI (EUR Hedged),310000000,0.0018,Full replication,ETF,Long-only,Yes,EUR,Currency hedged,0.1048,3 March 2021,Distributing,Annually,Luxembourg,Amundi ETF,0.0018,False,LU2297533809,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.3019,0.6240,NaN,0.0193,0.0344,0.0204,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0157,0.0157,0.0162,NaN,NaN,NaN,True,True,True,NaN,NaN,NaN,True,NaN,NaN,NaN,True,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,True,NaN,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
345,https://www.justetf.com/en/etf-profile.html?isin=IE00BFZPF439,0.0782,0.1089,0.1222,1.19,-0.36,0.05,-0.0338,-0.2794,-0.2873,-0.2873,0.0614,0.97,0.0149,-0.0186,0.0000,0.0155,0.0935,-0.1140,0.0334,0.0890,-0.0021,-0.1279,0.0388,0.0559,79,0.1985,iBoxx® USD Contingent Convertible Liquid Developed Market AT1 (EUR Hedged),266000000,0.0039,Full replication,ETF,Long-only,No,EUR,Currency hedged,0.0782,25 June 2018,Distributing,Quarterly,Ireland,Invesco,0.0039,False,IE00BFZPF439,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.1728,NaN,NaN,0.3880,NaN,NaN,NaN,0.2473,NaN,0.0584,NaN,NaN,NaN,NaN,NaN,NaN,0.1335,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0097,0.0099,0.0103,0.0090,0.0109,NaN,NaN,True,True,NaN,NaN,NaN,True,NaN,NaN,NaN,True,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
util.startLoop()

ib = IB()
ib.connect('127.0.0.1', 7497, clientId=1)

# historical_data = []
# for etf in filled:
#     contract = Stock(etf[0], 'SMART', 'EUR')
#     data = ib.reqHistoricalData(
#         contract, 
#         endDateTime='', 
#         durationStr='3 Y',
#         barSizeSetting='1 hour', 
#         whatToShow= 'MIDPOINT', 
#         useRTH=True)
#     historical_data.append(etf+[data])

ib.disconnect()