In [2]:
import networkx as nx
import matplotlib.pyplot as plt
import pandas as pd
from statistics import mean
from statistics import stdev
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:
# School data
madrid = 508/3481 
barcelona = 168/3500 
valencia = 127/1682 
sevilla = 88/1545 
malaga = 70/1146
cordoba = 47/721    
vizcaya = 21/688
zaragoza = 56/588
las_palmas = 34/580
spain_picrates = [madrid, barcelona, valencia, sevilla, malaga, cordoba, vizcaya, zaragoza, las_palmas]

mex_city = 26/1941
estado_mex = 14/2029
mex_rates = [mex_city, estado_mex]

# Site analytics
spain_views = 22891267
spain_school_total = 30782
spain_click = 122639

mexico_views = 2865062
mex_school_total = 27368
mex_click = 2828

monthly_views = round(mean([356100, 391900, 356100]))
competition_monthly_views = round(mean([103000, 57800, 88000]))

In [4]:
# Stats April 13- April 28

clients = [25, 0, 69, 0, 41, 2, 39, 1, 0, 165, 0, 165,55,0,21,2,17,1,25,0,43,1,42,0,29,0,40,2,13,2,23,2,28,0]
ex_clients = [1, 0, 2, 0, 3, 0, 6, 0,0,6,0,6,4, 0,5,0,3,0, 3,0,2,0,8,0,1,0,6,0,2,0,0,0,4,0]
inactives = [39, 17, 113, 31, 134, 59, 243, 25,20,125,20,125, 124, 17,91,5,45,16,93,16,109,24,159,35,141,33,136,18,33,4,38,6,81,15]
frees = [8, 0, 23, 1, 25, 1, 45, 0,0,79,0,79, 25, 0,18,1,14,0,12,1,29,1,56,3,37,0,30,1,8,0,12,0,19,0]

for i in range(len(clients) - 1, -1, -1):
    if clients[i] < 5:
        clients.pop(i)
        ex_clients.pop(i)
        inactives.pop(i)
        frees.pop(i)

picrate = sum(clients) / (sum(clients) + sum(ex_clients) + sum(frees))
clients

[25, 69, 41, 39, 165, 165, 55, 21, 17, 25, 43, 42, 29, 40, 13, 23, 28]

In [5]:
# % schools with picturs
spain_avg_picrate = mean(spain_picrates)
spain_std_picrate = stdev(spain_picrates)
mex_avg_picrate = (madrid - spain_avg_picrate) / madrid * mex_city

# % schools subscribed
spain_avg_subrate = spain_avg_picrate * picrate
spain_std_subrate = spain_std_picrate * picrate
mex_avg_subrate = mex_avg_picrate * picrate

# Range of subscribed schools
eSpain_rates = [spain_avg_subrate - spain_std_subrate, spain_avg_subrate, spain_avg_subrate + spain_std_subrate]

num_spain_subbed = [rate * spain_school_total for rate in eSpain_rates]
num_mex_subbed = mex_avg_subrate * mex_school_total
num_subbed_school = [rate + num_mex_subbed for rate in num_spain_subbed]
total_school = mex_school_total + spain_school_total

# Money
multiples = [2.3, 7.7]
prices = [260, 600, 700, 968, 1200, 653, 726, 968, 540, 726, 90, 726, 120, 726, 480, 726, 680, 726, 303, 726, 726, 242, 726, 100, 726, 340, 680, 136,120,726,120,600,726,726,220,726,726]
ePrices = [mean(prices) - stdev(prices), mean(prices), mean(prices) + stdev(prices)]

####################################
num_subbed_school = [2500]  # Set to school conversion rate
ePrices = [700] # Set to actual annual ARPU
employees = [3, 7] # Abhijit, Estefania, Ana Ortiz, Vishav, Avishek Prashad
ceo = 3
ceo_mult = 3

arr = [ePrices[0] * num_subbed_school[0], mean(ePrices) * mean(num_subbed_school), ePrices[-1] * num_subbed_school[-1]]
arr = [round(r) for r in arr]
ePrices, arr, mean(num_subbed_school), spain_avg_picrate, spain_std_picrate

([700],
 [485800, 485800, 485800],
 694,
 0.07078329564306449,
 0.033302730294297714)

In [6]:
max_num_schools_worth_10k = round(10000/ePrices[0])
min_num_schools_worth_10k = round(10000/ePrices[-1])

# print(f'{round(monthly_views/competition_monthly_views, 2)}x more views than next best competitor')
print(f'Spain school conversion rate: {round(num_subbed_school[0]/spain_school_total*100,2)}%  -  {round(mean(num_subbed_school)/spain_school_total*100,2)}%  -  {round(num_subbed_school[-1]/spain_school_total*100,2)}%')
print(f'ARR: ${"{:,}".format(arr[0])}  -  ${"{:,}".format(round(mean(arr)))}  -  ${"{:,}".format(arr[-1])}')
print(f'eValuation: ${"{:,}".format(round(arr[0]*multiples[0]))}  -  ${"{:,}".format(round(mean(arr)*mean(multiples)))}  -  ${"{:,}".format(round(arr[-1]*multiples[-1]))}')
print(f'10k = {min_num_schools_worth_10k}  -  {max_num_schools_worth_10k} new schools')
print(f'10k = {round((min_num_schools_worth_10k/spain_school_total)*100, 2)}%  -  {round((max_num_schools_worth_10k/spain_school_total)*100, 2)}% in market conversion rate')
print(f'10k = {round((min_num_schools_worth_10k/mean(num_subbed_school))*100, 2)}%  -  {round((max_num_schools_worth_10k/mean(num_subbed_school))*100, 2)}% more subcribed schools')
print(f'My estimated salary = ${"{:,}".format(round(arr[0]/(employees[-1] + ceo * ceo_mult),2))}  -  ${"{:,}".format(round(mean(arr)/(mean(employees) + ceo * ceo_mult),2))}  -  ${"{:,}".format(round(arr[-1]/(employees[0] + ceo * ceo_mult),2))}')

Spain school conversion rate: 2.25%  -  2.25%  -  2.25%
ARR: $485,800  -  $485,800  -  $485,800
eValuation: $1,117,340  -  $2,429,000  -  $3,740,660
10k = 14  -  14 new schools
10k = 0.05%  -  0.05% in market conversion rate
10k = 2.02%  -  2.02% more subcribed schools
My estimated salary = $30,362.5  -  $34,700.0  -  $40,483.33

In [7]:
finances = {
    'country':['spain', 'mexico', 'total'],
    'market_size': [spain_school_total, mex_school_total, spain_school_total + mex_school_total],
    'annual_market_value': [round(spain_school_total * mean(ePrices)), round(mex_school_total * mean(ePrices)), round((spain_school_total + mex_school_total)* mean(ePrices))],
    '%_market_subbed': [spain_avg_subrate, mex_avg_subrate, (spain_avg_subrate + mex_avg_subrate)/2],
    'views_reported': [22891267, 2865062, 22891267 + 2865062],
    'eMonthly_views': [monthly_views, round(monthly_views*mexico_views/spain_views),monthly_views + round(monthly_views*mexico_views/spain_views) ],
    'eYear_views': [round(monthly_views*12), round(monthly_views*mexico_views/spain_views*12), round(monthly_views*12) + round(monthly_views*mexico_views/spain_views*12)],
    'user%_per_country': [0.7878, 0.1142, 0.7878 + 0.1142],
    'clicks': [122639, 2828, 122639 + 2828],
    'viewtime(s)': ['173-536', '173-536', '173-536'],
    'view/user': ['1.7-2.17', '1.7-2.17', '1.7-2.17'],
    'bounce': ['69.62-69.74', '69.62-69.74', '69.62-69.74']
}
fin_df = (pd.DataFrame(finances))
fin_df

,country,market_size,annual_market_value,%_market_subbed,views_reported,eMonthly_views,eYear_views,user%_per_country,clicks,viewtime(s),view/user,bounce
0,spain,30782,21547400,0.041842,22891267,368033,4416396,0.7878,122639,173-536,1.7-2.17,69.62-69.74
1,mexico,27368,19157600,0.004078,2865062,46063,552754,0.1142,2828,173-536,1.7-2.17,69.62-69.74
2,total,58150,40705000,0.022960,25756329,414096,4969150,0.9020,125467,173-536,1.7-2.17,69.62-69.74

# After taxes 
40k =IVA=> 31,600 =IRPF+SS=> 25,267
42k =IVA=> 33,180 =IRPF+SS=> 26,407
45k =IVA=> 35,550 =IRPF+SS=> 28,118

# SS milestones
322:   33,151.89 => 26190
328:   37,922.78 => 29959
348:  44,44.03 => 35110
389:   50,974.68 => 40270

# Pay exected
30k autonomo = 39k real

## 2024 salary stats
30.1k average
25.6k median
40.6k tech average
45.1k int specialist average

442k Investment 2019
- Santiago Bernal Piñeiro 
- Borja García-Fuster
- Felipe Navio
- Savvy Capital 
- Patricia Ferruz
- Manuel Robles

6 - 10 employees
- Abhijit B - Dev
- Ana Ortiz Roca Mexico manager
- Ruben CEO
- Andoitz CTO
- Ignacio CEO
- Estefanía S. sales

Angels
- Santiago Bernal Piñeiro 
- Amalia Fontan Yanes

In [8]:
data = {
"website": [
"Micole.net",
"todoeduca.com",
"buscocolegio.com",
"colesyguardes.es",
"greatschools.org",
"niche.com",
"commonapp.org"],

# Rank can be a list or another dictionary if you want to keep track of historical ranks
"country rank": [
{"current": 5149, "previous": [4294, 5176]},
{"current": 27914, "previous": [24203, 15365]},
{"current": 24957, "previous": [24787, 23991]},
{"current": 23329, "previous": [24370, 21077]},
{"current": 3528, "previous": [3610, 3812]},
{"current": 1435, "previous": [1522, 1408]},
{"current": 968, "previous": [2539, 3394]}],

"category rank": [
{"current": 201, "previous": [193, 202]},
{"current": 803, "previous": [779, 511]},
{"current": 735, "previous": [795, 742]},
{"current": 690, "previous": [785, 665]},
{"current": 112, "previous": [129, 126]},
{"current": 29, "previous": [35, 29]},
{"current": 11, "previous": [80, 97]}],

"users": [
{"female": 51.81, "male": 48.19},
{"female": 61.47, "male": 38.53},
{"female": 48.81, "male": 51.19},
{"female": 56.8, "male": 43.2},
{"female": 55.75, "male": 44.25},
{"female": 56.24, "male":43.76},
{"female": 58.94, "male": 41.07}],

"age": [{"18-24": 13.87, "25-34": 20.07, "35-44": 20.39,
"45-54": 18.58, "55-64": 17.12, "65+": 9.97}, {"18-24": 17.94, "25-34": 20.77, "35-44": 22.81,
"45-54": 18.4, "55-64": 12.38, "65+": 7.71}, {"18-24": 12.01, "25-34": 24.86, "35-44": 23.74,
"45-54": 16.69, "55-64": 13.15, "65+": 9.55}, {"18-24": 10.77, "25-34": 18.8, "35-44": 22.46,
"45-54": 19.25, "55-64": 18.83, "65+": 9.89}, {"18-24": 12.84, "25-34": 29.74, "35-44": 22.23,
"45-54": 17.23, "55-64": 11.27, "65+": 6.69}, {"18-24": 26.92, "25-34": 24.74, "35-44": 17.79,
"45-54": 14.5, "55-64": 9.7, "65+": 6.36}, {"18-24": 52.86, "25-34": 18.3, "35-44": 12.54,
"45-54": 8.06, "55-64": 4.21, "65+": 4.06}],

"traffic_jan": [356.1, 103, 60.6, 58.2, 3400, 8500, 12500],
"outgoing_links": [2, 1, 0, 0, 18, 856, 159],
"traffic_feb": [391.9, 57.8, 58.3, 503, 3100, 7500, 4300],
"traffic_mar": [356.1, 88, 62.7, 57.9, 3122, 8600, 3300],
"bounce_rate": [69.74, 70.26, 70.87, 75.48, 51.76, 48.76, 27.03],
"page_views": [2.17, 2.31, 1.76, 2.79, 3.28, 3.87, 8.90],
"session_time": ["00:02:53", "00:02:13", "00:01:13", "00:01:56", "00:02:51", "00:03:22", "00:06:24"],

"Backlinks": [{"direct": 13.75, "referals": 3.52, "organic": 82.24, "paid search": 0, "social": .48, "mail": 0, "display": 0},
              {"direct": 18.24, "referals": .88, "organic": 80.68, "paid search": 0, "social": .2, "mail": 0, "display": 0},
              {"direct": 12.09, "referals": .33, "organic": 87.58, "paid search": 0, "social": 0, "mail": 0, "display": 0},
              {"direct": 8.95, "referals": 0, "organic": 90.98, "paid search": 0, "social": .06, "mail": 0, "display": 0},
              {"direct": 26.72, "referals": 12.4, "organic": 58.81, "paid search": .32, "social": .9, "mail": .85, "display": 0},
              {"direct": 19.59, "referals": 3.78, "organic": 72.27, "paid search": 1.36, "social": .66, "mail": .84, "display": 1.49},
              {"direct": 76.2, "referals": 3.72, "organic": 17.77, "paid search": 0, "social": .93, "mail": 1.35, "display": .04},],

"keywords": [7.3, 4.4, 3.4, 1.2, 14.2, 19.5, 7.1],
"referals": [8, 1, 0, 0, 32, 110, 178],
}

df = pd.DataFrame(data)

def unpack_rankings_and_age(df):
  for idx in df.index:
    rankings = df.loc[idx, "country rank"]
    df.at[idx, "country_jan"] = rankings.get("current")
    df.at[idx, "country_feb"] = rankings.get("previous", [])[0]  # Handle empty list
    df.at[idx, "country_mar"] = rankings.get("previous", [])[1]  # Handle empty list
    
    rankings = df.loc[idx, "category rank"]
    df.at[idx, "category_jan"] = rankings.get("current")
    df.at[idx, "category_feb"] = rankings.get("previous", [])[0]  # Handle empty list
    df.at[idx, "category_mar"] = rankings.get("previous", [])[1]  # Handle empty list
    
    age_dict = df.loc[idx, "age"]
    for age_range, value in age_dict.items():
      df.at[idx, age_range] = value

    gender_dict = df.loc[idx, "users"]
    for gender_range, value in gender_dict.items():
      df.at[idx, gender_range] = value
    
    gender_dict = df.loc[idx, "Backlinks"]
    for gender_range, value in gender_dict.items():
      df.at[idx, gender_range] = value
  
  # Remove original columns after unpacking
  del df["country rank"]
  del df["category rank"]
  del df["age"]
  del df["users"]
  del df["Backlinks"]
  return df

df = pd.DataFrame(data)
df = unpack_rankings_and_age(df.copy())  # Make a copy to avoid modifying original
df

C:\Users\Alex\AppData\Local\Temp\ipykernel_15964\1756869689.py:92: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '3.52' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.at[idx, gender_range] = value

,website,traffic_jan,outgoing_links,traffic_feb,traffic_mar,bounce_rate,page_views,session_time,keywords,referals,country_jan,country_feb,country_mar,category_jan,category_feb,category_mar,18-24,25-34,35-44,45-54,55-64,65+,female,male,direct,organic,paid search,social,mail,display
0,Micole.net,356.1,2,391.9,356.1,69.74,2.17,00:02:53,7.3,3.52,5149.0,4294.0,5176.0,201.0,193.0,202.0,13.87,20.07,20.39,18.58,17.12,9.97,51.81,48.19,13.75,82.24,0.00,0.48,0.00,0.00
1,todoeduca.com,103.0,1,57.8,88.0,70.26,2.31,00:02:13,4.4,0.88,27914.0,24203.0,15365.0,803.0,779.0,511.0,17.94,20.77,22.81,18.40,12.38,7.71,61.47,38.53,18.24,80.68,0.00,0.20,0.00,0.00
2,buscocolegio.com,60.6,0,58.3,62.7,70.87,1.76,00:01:13,3.4,0.33,24957.0,24787.0,23991.0,735.0,795.0,742.0,12.01,24.86,23.74,16.69,13.15,9.55,48.81,51.19,12.09,87.58,0.00,0.00,0.00,0.00
3,colesyguardes.es,58.2,0,503.0,57.9,75.48,2.79,00:01:56,1.2,0.00,23329.0,24370.0,21077.0,690.0,785.0,665.0,10.77,18.80,22.46,19.25,18.83,9.89,56.80,43.20,8.95,90.98,0.00,0.06,0.00,0.00
4,greatschools.org,3400.0,18,3100.0,3122.0,51.76,3.28,00:02:51,14.2,12.40,3528.0,3610.0,3812.0,112.0,129.0,126.0,12.84,29.74,22.23,17.23,11.27,6.69,55.75,44.25,26.72,58.81,0.32,0.90,0.85,0.00
5,niche.com,8500.0,856,7500.0,8600.0,48.76,3.87,00:03:22,19.5,3.78,1435.0,1522.0,1408.0,29.0,35.0,29.0,26.92,24.74,17.79,14.50,9.70,6.36,56.24,43.76,19.59,72.27,1.36,0.66,0.84,1.49
6,commonapp.org,12500.0,159,4300.0,3300.0,27.03,8.90,00:06:24,7.1,3.72,968.0,2539.0,3394.0,11.0,80.0,97.0,52.86,18.30,12.54,8.06,4.21,4.06,58.94,41.07,76.20,17.77,0.00,0.93,1.35,0.04

In [9]:
# User data
user_data = {
    "Micole.net": {"spain": 78.78, "mexico": 11.42, "peru": 2.07, "russia": 1.07, "Ecuador": 0.68, "other_country": 5.98},
    "todoeduca.com": {"spain": 89.16, "peru": 5.26, "portugal": 1.19, "US": 1.09, "Argentina": 1.06, "other_country": 2.23},
    "buscocolegio.com": {"spain": 95.45, "US": 2.26, "Brazil": 1.15, "Italy": 1.14},
    "colesyguardes.es": {"spain": 96.07, "US": 2.24, "portugal": 1.69},
    "greatschools.org": {"US": 93.09, "Canada": 1, "Philipines": 0.94, "India": 0.74, "UK": 0.41, "other_country": 3.82},
    "niche.com": {"US": 91.21, "Canada": 0.56, "Brazil": 0.46, "Thailand": 0.45, "India": 0.43, "other_country": 6.86},
    "commonapp.org": {"US": 78.7, "Ghana": 1.78, "India": 1.14, "UAE": 0.81, "S Korea": 0.79, "other_country": 16.78}
}

# Convert user data to DataFrame
df_user_data = (pd.DataFrame(user_data).transpose())/100

# Merge the two DataFrames
df = pd.merge(df, df_user_data, left_on='website', right_index=True, how='left')



# Referral data
referral_data = {
    "Micole.net": {"backlinks": 8, "news": 60.7, "search engines": 7.59, "education": 7.59, "other": 24.12},
    "todoeduca.com": {"backlinks": 1, "search engines": 100},
    "buscocolegio.com": {},
    "colesyguardes.es": {},
    "greatschools.org": {"backlinks": 32, "real estate": 97.26, "search engines": 0.5, "education": 0.46, "computer electronics": 0.36, "restaurants": 0.27, "other": 1.16},
    "niche.com": {"backlinks": 110, "grants scholarships": 53, "news": 19, "universities": 8.27, "real estate": 7.57, "education": 2.95, "other": 9.06},
    "commonapp.org": {"backlinks": 178, "universities": 93.23, "education": 2.44, "search engines": 1.13, "business services": 0.44, "philanthropy": 0.44, "other": 2.33}
}

# Convert referral data to DataFrame
df_referral_data = (pd.DataFrame(referral_data).transpose())/100

# Merge the two DataFrames
df = pd.merge(df, df_referral_data, left_on='website', right_index=True, how='left')

In [10]:
# New data
new_data = {
    "Micole.net": {"total": 2, "Linkedin": 78.59, "Youtube": 21.41, "outgoing": 2},
    "todoeduca.com": {"total": 1, "Youtube": 100, "outgoing": 1},
    "buscocolegio.com": {"total": 0, "outgoing": 0},
    "colesyguardes.es/": {"total": 1, "Whatsapp": 100, "outgoing": 0},
    "greatschools.org": {"total": 7, "Youtube": 28.9, "facebook": 24.4, "reddit": 21.8, "twitter": 10.65, "pinterest": 6.64, "other_socialmedia": 7.55, "outgoing": 18},
    "niche.com": {"total": 19, "Youtube": 36.5, "linkedin": 16.96, "facebook": 15.55, "reddit": 14.45, "insta": 3.61, "other_socialmedia": 12.85, "outgoing": 856},
    "commonapp.org": {"total": 14, "Youtube": 70.65, "reddit": 10.57, "instagram": 7.14, "facebook": 4.27, "discord": 0.269, "other_socialmedia": 4.69, "outgoing": 159}
}

# Convert new data to DataFrame
df_new_data = (pd.DataFrame(new_data).transpose())/100

# Merge the two DataFrames
df = pd.merge(df, df_new_data, left_on='website', right_index=True, how='left')

In [11]:
df.columns = df.columns.str.lower().str.replace(' ', '_')
df = df[['website', 'country_jan', 'country_feb', 'country_mar', 'category_jan',
       'category_feb', 'category_mar', 'female', 'male', '18-24', '25-34', '35-44', '45-54',
       '55-64', '65+', 'spain', 'mexico', 'peru', 'russia',
       'ecuador', 'portugal', 'us', 'argentina', 'brazil',
       'italy', 'canada', 'philipines', 'india', 'uk', 'thailand', 'ghana',
       'uae', 's_korea', 'other_country', 'traffic_jan', 'traffic_feb',
       'traffic_mar', 'bounce_rate', 'page_views', 'session_time', 'keywords',
       'referals',  'direct', 'organic', 'paid_search',
       'social', 'mail', 'display', 'backlinks', 'news', 'search_engines', 'education',
       'other', 'real_estate', 'computer_electronics', 'restaurants',
       'grants_scholarships', 'universities', 'business_services',
       'philanthropy', 'total', 'youtube', 'outgoing', 'whatsapp',
       'facebook', 'reddit', 'twitter', 'pinterest', 'other_socialmedia',
       'linkedin', 'insta', 'instagram', 'discord', 'outgoing_links', ]]
df = df.rename(columns={'total': 'num_social', 'backlinks': 'num_backlinks', 'country_jan': 'jan_country_rank', 'country_feb': 'feb_country_rank', 'country_mar': 'mar_country_rank', 'category_jan': 'jan_category_rank', 'category_feb': 'feb_category_rank', 'category_mar': 'mar_category_rank', 'traffic_jan': 'jan_traffic', 'traffic_feb': 'feb_traffic', 'traffic_mar': 'mar_traffic', 'page_views':'page_views_per_user', 'keywords':'num_keywords', 'other_country':'other_countries'})
df ['mar_traffic'] = df ['mar_traffic'] * 1000
df ['feb_traffic'] = df ['feb_traffic'] * 1000
df ['jan_traffic'] = df ['jan_traffic'] * 1000
df ['num_keywords'] = df ['num_keywords'] * 1000
df ['female'] = df ['female'] / 100
df ['male'] = df ['male'] / 100
df ['18-24'] = df ['18-24'] / 100
df ['25-34'] = df ['25-34'] / 100
df ['35-44'] = df ['35-44'] / 100
df ['45-54'] = df ['45-54'] / 100
df ['55-64'] = df ['55-64'] / 100
df ['65+'] = df ['65+'] / 100
df ['referals'] = df ['referals'] / 100
df ['direct'] = df ['direct'] / 100
df ['organic'] = df ['organic'] / 100
df ['paid_search'] = df ['paid_search'] / 100
df ['social'] = df ['social'] / 100
df ['mail'] = df ['mail'] / 100
df ['display'] = df ['display'] / 100
df ['num_backlinks'] = df ['num_backlinks'] * 100
df ['num_social'] = df ['num_social'] * 100

def time_to_seconds(t):
    h, m, s = map(int, t.split(':'))
    return h * 3600 + m * 60 + s

df['session_time'] = df['session_time'].apply(time_to_seconds)

In [12]:
# df.to_csv(f'micole_competition.csv', index=False)
df.sort_values(by='mar_category_rank')

,website,jan_country_rank,feb_country_rank,mar_country_rank,jan_category_rank,feb_category_rank,mar_category_rank,female,male,18-24,25-34,35-44,45-54,55-64,65+,spain,mexico,peru,russia,ecuador,portugal,us,argentina,brazil,italy,canada,philipines,india,uk,thailand,ghana,uae,s_korea,other_countries,jan_traffic,feb_traffic,mar_traffic,bounce_rate,page_views_per_user,session_time,num_keywords,referals,direct,organic,paid_search,social,mail,display,num_backlinks,news,search_engines,education,other,real_estate,computer_electronics,restaurants,grants_scholarships,universities,business_services,philanthropy,num_social,youtube,outgoing,whatsapp,facebook,reddit,twitter,pinterest,other_socialmedia,linkedin,linkedin,insta,instagram,discord,outgoing_links
5,niche.com,1435.0,1522.0,1408.0,29.0,35.0,29.0,0.5624,0.4376,0.2692,0.2474,0.1779,0.1450,0.0970,0.0636,NaN,NaN,NaN,NaN,NaN,NaN,0.9121,NaN,0.0046,NaN,0.0056,NaN,0.0043,NaN,0.0045,NaN,NaN,NaN,0.0686,8500000.0,7500000.0,8600000.0,48.76,3.87,202,19500.0,0.0378,0.1959,0.7227,0.0136,0.0066,0.0084,0.0149,110.0,0.190,NaN,0.0295,0.0906,0.0757,NaN,NaN,0.53,0.0827,NaN,NaN,19.0,0.3650,8.56,NaN,0.1555,0.1445,NaN,NaN,0.1285,NaN,0.1696,0.0361,NaN,NaN,856
6,commonapp.org,968.0,2539.0,3394.0,11.0,80.0,97.0,0.5894,0.4107,0.5286,0.1830,0.1254,0.0806,0.0421,0.0406,NaN,NaN,NaN,NaN,NaN,NaN,0.7870,NaN,NaN,NaN,NaN,NaN,0.0114,NaN,NaN,0.0178,0.0081,0.0079,0.1678,12500000.0,4300000.0,3300000.0,27.03,8.90,384,7100.0,0.0372,0.7620,0.1777,0.0000,0.0093,0.0135,0.0004,178.0,NaN,0.0113,0.0244,0.0233,NaN,NaN,NaN,NaN,0.9323,0.0044,0.0044,14.0,0.7065,1.59,NaN,0.0427,0.1057,NaN,NaN,0.0469,NaN,NaN,NaN,0.0714,0.00269,159
4,greatschools.org,3528.0,3610.0,3812.0,112.0,129.0,126.0,0.5575,0.4425,0.1284,0.2974,0.2223,0.1723,0.1127,0.0669,NaN,NaN,NaN,NaN,NaN,NaN,0.9309,NaN,NaN,NaN,0.0100,0.0094,0.0074,0.0041,NaN,NaN,NaN,NaN,0.0382,3400000.0,3100000.0,3122000.0,51.76,3.28,171,14200.0,0.1240,0.2672,0.5881,0.0032,0.0090,0.0085,0.0000,32.0,NaN,0.0050,0.0046,0.0116,0.9726,0.0036,0.0027,NaN,NaN,NaN,NaN,7.0,0.2890,0.18,NaN,0.2440,0.2180,0.1065,0.0664,0.0755,NaN,NaN,NaN,NaN,NaN,18
0,Micole.net,5149.0,4294.0,5176.0,201.0,193.0,202.0,0.5181,0.4819,0.1387,0.2007,0.2039,0.1858,0.1712,0.0997,0.7878,0.1142,0.0207,0.0107,0.0068,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0598,356100.0,391900.0,356100.0,69.74,2.17,173,7300.0,0.0352,0.1375,0.8224,0.0000,0.0048,0.0000,0.0000,8.0,0.607,0.0759,0.0759,0.2412,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.2141,0.02,NaN,NaN,NaN,NaN,NaN,NaN,0.7859,NaN,NaN,NaN,NaN,2
1,todoeduca.com,27914.0,24203.0,15365.0,803.0,779.0,511.0,0.6147,0.3853,0.1794,0.2077,0.2281,0.1840,0.1238,0.0771,0.8916,NaN,0.0526,NaN,NaN,0.0119,0.0109,0.0106,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0223,103000.0,57800.0,88000.0,70.26,2.31,133,4400.0,0.0088,0.1824,0.8068,0.0000,0.0020,0.0000,0.0000,1.0,NaN,1.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0000,0.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
3,colesyguardes.es,23329.0,24370.0,21077.0,690.0,785.0,665.0,0.5680,0.4320,0.1077,0.1880,0.2246,0.1925,0.1883,0.0989,0.9607,NaN,NaN,NaN,NaN,0.0169,0.0224,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58200.0,503000.0,57900.0,75.48,2.79,116,1200.0,0.0000,0.0895,0.9098,0.0000,0.0006,0.0000,0.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,buscocolegio.com,24957.0,24787.0,23991.0,735.0,795.0,742.0,0.4881,0.5119,0.1201,0.2486,0.2374,0.1669,0.1315,0.0955,0.9545,NaN,NaN,NaN,NaN,NaN,0.0226,NaN,0.0115,0.0114,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60600.0,58300.0,62700.0,70.87,1.76,73,3400.0,0.0033,0.1209,0.8758,0.0000,0.0000,0.0000,0.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [1]:
correlation_matrix = df.drop(['website'], axis=1).corr()

plt.figure(figsize=(15,15))
plt.imshow(correlation_matrix, cmap='coolwarm')  # Adjust 'coolwarm' for preferred colormap

# Add labels and title
plt.colorbar(label='Correlation Coefficient')
plt.xticks(range(len(correlation_matrix.columns)), correlation_matrix.columns, rotation=90)
plt.yticks(range(len(correlation_matrix.columns)), correlation_matrix.columns)
plt.title('Correlation Matrix Heatmap')

# Display the plot
plt.show()

NameError: name 'df' is not defined